// Level 2 SIEM investigation cases. Same schema as content/siem-cases.js (and the ambiguous
// fields documented there), plus `tier: 'l2'`. They unlock from Level 2 skills.
// All data is fictional: RFC 5737 / private IPs and reserved example domains.

export const L2_SIEM_CASES = [
  // ------------------------------------------------------------------ L2-1: phishing with headers
  {
    id: 'siem-l2-payroll-phish',
    tier: 'l2',
    title: 'The payslip that wasn\'t',
    difficulty: 2,
    date: 'Tue 22 Sep 2026',
    summary: 'A user reports a payroll email. Read the headers, then find out who clicked, who typed a password and what the attacker did next.',
    requires: { skills: ['l2-phishing'] },
    alert: {
      id: 'ALRT-5210',
      name: 'User-reported phishing: payroll login page',
      severity: 'medium',
      time: '09:31:10',
      host: 'MAIL-GW',
      user: 'emma',
      source: 'Report-phish button',
      detail: 'emma@corp.example reported "Action required: confirm your September payslip" as phishing.',
    },
    logs: [
      { id: 'p01', t: '08:55:02', src: 'email', host: 'MAIL-GW', user: 'lena', type: 'Delivered', msg: 'To lena@corp.example  From: "IT Service Desk" <servicedesk@corp.example>  Subject: "Planned maintenance Saturday"  spf=pass dkim=pass header.d=corp.example dmarc=pass' },
      { id: 'p02', t: '09:02:14', src: 'email', host: 'MAIL-GW', user: 'emma', type: 'Delivered', msg: 'To emma@corp.example  From: "HR Payroll" <payroll@corp-example-hr.example>  Return-Path: <bounce@mailer.corp-example-hr.example>  Subject: "Action required: confirm your September payslip"  Sending IP: 203.0.113.140' },
      { id: 'p03', t: '09:02:14', src: 'email', host: 'MAIL-GW', user: 'emma', type: 'Auth results', msg: 'Authentication-Results: spf=pass smtp.mailfrom=mailer.corp-example-hr.example; dkim=pass header.d=corp-example-hr.example; dmarc=pass header.from=corp-example-hr.example  (sender domain first seen today; registered 2 days ago)' },
      { id: 'p04', t: '09:02:15', src: 'email', host: 'MAIL-GW', user: '(14 recipients)', type: 'Delivered', msg: 'Same message (same sender, subject and URL) also delivered to 14 mailboxes on the hr-all and finance-all lists, including jonas@corp.example' },
      { id: 'p05', t: '09:02:15', src: 'email', host: 'MAIL-GW', user: 'emma', type: 'URL in message', msg: 'Link target: https://payroll.corp-example-hr.example/sso/login   Display text: "https://payroll.corp.example"' },
      { id: 'p06', t: '09:10:43', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'WS-HR-04 (10.10.6.14) query A payroll.corp-example-hr.example -> 203.0.113.140' },
      { id: 'p07', t: '09:10:44', src: 'proxy', host: 'WS-HR-04', user: 'emma', type: 'GET 200', msg: 'emma WS-HR-04 GET https://payroll.corp-example-hr.example/sso/login 200 text/html (page title "Corp SSO - Sign in")' },
      { id: 'p08', t: '09:11:31', src: 'proxy', host: 'WS-HR-04', user: 'emma', type: 'POST 302', msg: 'emma WS-HR-04 POST https://payroll.corp-example-hr.example/sso/login 302 -> https://payroll.corp.example/ (form fields: username, password, otp)' },
      { id: 'p09', t: '09:13:02', src: 'proxy', host: 'WS-FIN-09', user: 'jonas', type: 'GET 200', msg: 'jonas WS-FIN-09 GET https://payroll.corp-example-hr.example/sso/login 200 text/html' },
      { id: 'p10', t: '09:14:10', src: 'proxy', host: 'WS-FIN-09', user: 'jonas', type: 'GET 200', msg: 'jonas WS-FIN-09 GET https://news.example.org/markets 200 text/html' },
      { id: 'p11', t: '09:20:00', src: 'idp', host: 'IDP', user: 'mateo', type: 'Sign-in success', msg: 'mateo@corp.example sign-in from 10.10.7.22 (corp office), device WS-SLS-02 (managed, compliant), MFA push approved' },
      { id: 'p12', t: '09:24:18', src: 'idp', host: 'IDP', user: 'emma', type: 'Sign-in success', msg: 'emma@corp.example sign-in to Webmail from 198.51.100.61 (hosting provider, new IP), device: unregistered, MFA: satisfied by one-time code entered 13 minutes earlier (session relayed)' },
      { id: 'p13', t: '09:26:40', src: 'idp', host: 'IDP', user: 'emma', type: 'New-InboxRule', msg: 'New-InboxRule by emma@corp.example from 198.51.100.61: name ".." if subject or body contains "payroll","bank","payslip" then move to "Conversation History" and mark as read' },
      { id: 'p14', t: '09:27:05', src: 'idp', host: 'IDP', user: 'emma', type: 'MailItemsAccessed', msg: 'MailItemsAccessed: 212 items read in Webmail by emma@corp.example from 198.51.100.61' },
      { id: 'p15', t: '09:29:30', src: 'idp', host: 'IDP', user: 'emma', type: 'Sign-in success', msg: 'emma@corp.example sign-in from 10.10.6.14 (corp office), device WS-HR-04 (managed), MFA push approved' },
      { id: 'p16', t: '09:31:10', src: 'email', host: 'MAIL-GW', user: 'emma', type: 'User report', msg: 'emma@corp.example reported "Action required: confirm your September payslip" as phishing' },
    ],
    key: [
      { id: 'k-domain', label: 'Lookalike sender that passes authentication for itself', rows: ['p02', 'p03'], why: 'SPF, DKIM and DMARC all pass, but only for corp-example-hr.example, a 2-day-old lookalike of corp.example. Authentication proves who sent it, not that they are trustworthy.' },
      { id: 'k-link', label: 'Link text shows the real portal, target is the lookalike', rows: ['p05'], why: 'The display text says payroll.corp.example; the real link goes to payroll.corp-example-hr.example.' },
      { id: 'k-post', label: 'emma submitted username, password and one-time code', rows: ['p08'], why: 'A POST of username, password and OTP to the lookalike, then a redirect to the real portal so nothing looks wrong: a credential-harvesting (adversary-in-the-middle) kit.' },
      { id: 'k-signin', label: 'Sign-in from a hosting IP using the relayed code', rows: ['p12'], why: 'Thirteen minutes after the POST, "emma" signs in from a hosting-provider IP on an unregistered device, with MFA satisfied by the code she typed into the fake page.' },
      { id: 'k-rule', label: 'Inbox rule hiding payroll and bank mail', rows: ['p13'], why: 'A meaningless rule name moving payroll and bank messages to an unused folder is classic business email compromise (T1564.008): the attacker hides replies while they redirect salary or payments.' },
    ],
    related: ['p04', 'p06', 'p07', 'p09', 'p14', 'p16'],
    verdict: 'tp',
    parQueries: 5,
    writeup: [
      { label: 'Names the lookalike domain', any: ['corp-example-hr', 'lookalike', 'look-alike'] },
      { label: 'Says credentials were submitted', any: ['post', 'credential', 'password', 'entered', 'submitted'] },
      { label: 'Describes the attacker sign-in', any: ['198.51.100.61', 'sign-in', 'signin', 'signed in', 'session'] },
      { label: 'Mentions the inbox rule', any: ['inbox rule', 'new-inboxrule', 'rule'] },
      { label: 'Scopes the other recipients', any: ['14', 'recipients', 'jonas', 'other users', 'mailboxes'] },
    ],
    explanation:
      'True positive: credential phishing leading to account compromise. A 2-day-old lookalike domain with its own valid SPF/DKIM/DMARC sent a fake payslip notice to 15 people. emma entered her username, password and one-time code; the kit relayed them and the attacker signed in from 198.51.100.61, read 212 emails and created an inbox rule to hide payroll and bank messages. jonas opened the page but no form submission is recorded.',
    strong: [
      'Read the headers first: everything passes, but for corp-example-hr.example. Alignment with a lookalike domain proves nothing about legitimacy.',
      'Scope in three layers: received (14 more mailboxes), clicked (proxy: emma and jonas), compromised (POST from emma, then a sign-in from a hosting IP).',
      'A one-time code does not stop a real-time relay kit: the attacker used emma\'s code within its session. Revoke sessions, not just the password.',
      'Contain: revoke emma\'s sessions, reset her password, remove the inbox rule, check sent mail and payroll changes; purge the message from all 15 mailboxes; block the domain and 203.0.113.140 / 198.51.100.61; confirm with jonas by phone that he did not type anything.',
      'Longer term: phishing-resistant MFA (FIDO2/passkeys) defeats this kind of relay.',
    ],
  },

  // ------------------------------------------------------------------ L2-2: loader via ISO + LNK
  {
    id: 'siem-l2-iso-loader',
    tier: 'l2',
    title: 'A parcel you weren\'t expecting',
    difficulty: 2,
    date: 'Wed 23 Sep 2026',
    summary: 'EDR flags a scheduled task created by rundll32. Follow it back to the delivery and forward to the C2, using the sandbox report.',
    requires: { skills: ['l2-malware'] },
    alert: {
      id: 'ALRT-5388',
      name: 'Scheduled task created by rundll32.exe',
      severity: 'high',
      time: '13:05:48',
      host: 'WS-ENG-05',
      user: 'ravi',
      source: 'EDR',
      detail: 'rundll32.exe created a scheduled task that runs a DLL from the user profile every 30 minutes.',
    },
    logs: [
      { id: 'm01', t: '12:58:01', src: 'process', host: 'WS-ENG-05', user: 'SYSTEM', type: 'Process create', msg: 'svchost.exe > GoogleUpdate.exe /ua /installsource scheduler (signed: Google LLC, valid)' },
      { id: 'm02', t: '13:01:10', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'WS-ENG-05 (10.10.8.35) query A teams.messaging.example -> 192.0.2.44' },
      { id: 'm03', t: '13:02:10', src: 'email', host: 'MAIL-GW', user: 'ravi', type: 'Delivered', msg: 'To ravi@corp.example  From: "Parcel Service" <notice@parcel-track-delivery.example>  Subject: "Delivery failed: reschedule your parcel"  Attachment: Parcel_88213.zip (contains Parcel_88213.iso)  spf=pass dkim=none dmarc=none' },
      { id: 'm04', t: '13:05:30', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'Image mount', msg: 'explorer.exe mounted Parcel_88213.iso (from Downloads\\Parcel_88213.zip) as drive E:. Contents: Parcel_88213.lnk, data\\pd.dll (hidden)' },
      { id: 'm05', t: '13:05:44', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'Process create', msg: 'explorer.exe > cmd.exe /c start rundll32 E:\\data\\pd.dll,DllRegisterServer   (launched by E:\\Parcel_88213.lnk)' },
      { id: 'm06', t: '13:05:45', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'Process create', msg: 'cmd.exe > rundll32.exe E:\\data\\pd.dll,DllRegisterServer   (pd.dll unsigned)' },
      { id: 'm07', t: '13:05:47', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'File create', msg: 'rundll32.exe wrote C:\\Users\\ravi\\AppData\\Roaming\\Intel\\igfxsvc.dll SHA256=5b7e2c9d0a4f6e8b1c3d5f7a9b0c2e4d6f8a1b3c5d7e9f0a2b4c6d8e0f1a3b5c' },
      { id: 'm08', t: '13:05:48', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'Process create', msg: 'rundll32.exe > schtasks.exe /create /sc minute /mo 30 /tn "Intel Graphics Refresh" /tr "rundll32 C:\\Users\\ravi\\AppData\\Roaming\\Intel\\igfxsvc.dll,Start"' },
      { id: 'm09', t: '13:06:02', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'WS-ENG-05 (10.10.8.35) query A cdn.stats-telemetry.example -> 198.51.100.23' },
      { id: 'm10', t: '13:06:03', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.8.35:52210 -> 198.51.100.23:443 bytes_out=412 bytes_in=96' },
      { id: 'm11', t: '13:07:04', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.8.35:52231 -> 198.51.100.23:443 bytes_out=412 bytes_in=96' },
      { id: 'm12', t: '13:08:03', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.8.35:52247 -> 198.51.100.23:443 bytes_out=412 bytes_in=96' },
      { id: 'm13', t: '13:10:00', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'Process create', msg: 'explorer.exe > chrome.exe (signed: Google LLC, valid)' },
      { id: 'm14', t: '13:12:30', src: 'firewall', host: 'FW-EDGE', user: '', type: 'DENY', msg: 'DENY TCP 203.0.113.9:40001 -> 10.10.8.35:3389 rule=default-deny' },
      { id: 'm15', t: '13:20:15', src: 'sandbox', host: 'SBX-01', user: 'soc', type: 'Detonation', msg: 'igfxsvc.dll (SHA256 5b7e2c9d...a3b5c): injects into explorer.exe (VirtualAllocEx, WriteProcessMemory, CreateRemoteThread); HTTPS POST /gate.php to 198.51.100.23 every ~60 s; verdict MALICIOUS (commodity loader)' },
      { id: 'm16', t: '13:21:00', src: 'sandbox', host: 'SBX-01', user: 'soc', type: 'Static', msg: 'pd.dll: PE32 DLL, .text entropy 7.86 (packed), exports DllRegisterServer and Start, compile timestamp 2009-03-14 (implausible, likely forged)' },
      { id: 'm17', t: '13:22:40', src: 'email', host: 'MAIL-GW', user: '(6 recipients)', type: 'Message trace', msg: 'Same sender and attachment hash delivered to 6 more mailboxes today (engineering and sales)' },
    ],
    key: [
      { id: 'k-delivery', label: 'ISO inside a ZIP from a lookalike courier', rows: ['m03', 'm04'], why: 'Containers such as ISO hide the payload from mail scanners and, on older builds, from mark-of-the-web warnings. A parcel notice from an unknown domain with no DKIM or DMARC is the lure.' },
      { id: 'k-exec', label: 'The LNK launched rundll32 with an unsigned DLL from the ISO', rows: ['m05', 'm06'], why: 'A shortcut that runs `rundll32 E:\\data\\pd.dll` is the user-execution step (T1204.002) using a signed Windows binary to load the malware (T1218.011).' },
      { id: 'k-persist', label: 'DLL copied to AppData and a 30-minute scheduled task', rows: ['m07', 'm08'], why: 'The loader copies itself under a fake Intel name and creates "Intel Graphics Refresh" to run it every 30 minutes: persistence via T1053.005 plus masquerading.' },
      { id: 'k-c2', label: 'Regular beacons to 198.51.100.23', rows: ['m09', 'm10', 'm11', 'm12'], why: 'A new domain, then identical small connections every ~60 seconds: command-and-control check-ins.' },
      { id: 'k-sbx', label: 'Sandbox: injection, /gate.php C2, packed DLL', rows: ['m15', 'm16'], why: 'Dynamic analysis confirms process injection and the C2 endpoint; static analysis shows packing and a forged timestamp. Together: malicious loader.' },
    ],
    related: ['m17'],
    verdict: 'tp',
    parQueries: 5,
    writeup: [
      { label: 'Describes the ISO/ZIP delivery', any: ['iso', 'zip', 'attachment', 'parcel'] },
      { label: 'Names the rundll32 / DLL execution', any: ['rundll32', 'pd.dll', 'igfxsvc', 'dll'] },
      { label: 'Mentions the scheduled task persistence', any: ['scheduled task', 'schtasks', 'intel graphics refresh', 'persistence'] },
      { label: 'Identifies the C2', any: ['198.51.100.23', 'gate.php', 'beacon', 'c2', 'stats-telemetry'] },
    ],
    explanation:
      'True positive: a commodity loader. A fake parcel notice delivered a ZIP containing an ISO. ravi mounted it and opened the shortcut, which ran rundll32 on a hidden, packed, unsigned DLL. The DLL copied itself into AppData as igfxsvc.dll, created a 30-minute scheduled task named "Intel Graphics Refresh", and began beaconing to cdn.stats-telemetry.example (198.51.100.23). The sandbox confirms injection into explorer.exe and HTTPS C2 to /gate.php. Six other people received the same attachment.',
    strong: [
      'Start from the alert (schtasks created by rundll32) and walk backwards in the process tree to the delivery, then forwards to the network.',
      'Use static and dynamic results together: packing and a forged timestamp (static) plus injection and C2 (dynamic).',
      'Ignore the noise: GoogleUpdate and chrome are signed and normal; the RDP DENY is unrelated internet scanning.',
      'Loaders sell access to other criminals, so a loader today can mean ransomware tomorrow: isolate WS-ENG-05, block the domain and IP, delete the task and DLL, and purge the email from the 6 other mailboxes (and check whether any of them mounted the ISO).',
      'Hunt with durable indicators: rundll32 loading DLLs from AppData or mounted drives, tasks named like hardware vendors, and the /gate.php URI.',
    ],
  },

  // ------------------------------------------------------------------ L2-3: ransomware rule, benign
  {
    id: 'siem-l2-mass-rename',
    tier: 'l2',
    title: 'Ransomware at 01:00?',
    difficulty: 2,
    date: 'Sat 26 Sep 2026',
    summary: 'The ransomware rule fires on the finance file server in the middle of the night: thousands of files renamed to a new extension.',
    requires: { skills: ['l2-alert-triage'] },
    alert: {
      id: 'ALRT-5503',
      name: 'Possible ransomware: mass file rename by a single process',
      severity: 'critical',
      time: '01:04:31',
      host: 'SRV-FS02',
      user: 'svc_vaultsync',
      source: 'EDR',
      detail: 'More than 3,000 files renamed to a new extension (.vsarc) by one process within 5 minutes on SRV-FS02.',
    },
    logs: [
      { id: 'r01', t: '00:30:12', src: 'winevt', host: 'SRV-FS02', user: 'svc_backup', type: 'Security 4624', msg: 'An account was successfully logged on. Account: svc_backup  Logon Type: 3  Source: 10.10.20.30 (SRV-BKP01)' },
      { id: 'r02', t: '00:59:00', src: 'ops', host: 'CHANGE-CAL', user: '', type: 'Change window', msg: 'CHG-5120 (approved): archive migration on SRV-FS02. VaultSync archiver moves Finance files older than 3 years to ARCH-COLD01 and leaves .vsarc stub files. Window Sat 01:00-04:00. Owner: storage team. Account: svc_vaultsync' },
      { id: 'r03', t: '01:00:05', src: 'winevt', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'Security 4624', msg: 'An account was successfully logged on. Account: svc_vaultsync  Logon Type: 5 (service)' },
      { id: 'r04', t: '01:00:07', src: 'process', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'Process create', msg: 'services.exe > C:\\Program Files\\VaultSync\\vsarchiver.exe --job archive-3y --share D:\\Shares\\Finance  (signed: VaultSync Software Ltd, valid; seen on this host monthly)' },
      { id: 'r05', t: '01:02:11', src: 'process', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'File rename', msg: 'vsarchiver.exe renamed 1,204 files under D:\\Shares\\Finance\\2021\\ to *.vsarc (original size 38 GB, stubs 4 KB each)' },
      { id: 'r06', t: '01:03:00', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'SRV-FS02 (10.10.20.22) query A arch-cold01.corp.example -> 10.10.20.80' },
      { id: 'r07', t: '01:04:30', src: 'process', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'File rename', msg: 'vsarchiver.exe renamed 2,340 files under D:\\Shares\\Finance\\2022\\ to *.vsarc' },
      { id: 'r08', t: '01:05:00', src: 'firewall', host: 'FW-CORE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.20.22:50122 -> 10.10.20.80:443 rule=fs-to-archive bytes_out=4.2GB' },
      { id: 'r09', t: '01:05:10', src: 'process', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'Network conn', msg: 'vsarchiver.exe -> 10.10.20.80:443 (ARCH-COLD01), TLS, 4.2 GB sent so far' },
      { id: 'r10', t: '01:06:30', src: 'firewall', host: 'FW-EDGE', user: '', type: 'DENY', msg: 'DENY TCP 198.51.100.200:40112 -> 10.10.20.22:445 rule=default-deny' },
      { id: 'r11', t: '01:08:00', src: 'ops', host: 'EDR', user: '', type: 'EDR query', msg: 'Search SRV-FS02, last 24 h: no vssadmin, wbadmin, bcdedit or wmic shadowcopy executions; no new files named *README*, *DECRYPT*, *RESTORE*; no outbound connections to the internet from vsarchiver.exe' },
      { id: 'r12', t: '01:10:00', src: 'process', host: 'SRV-FS02', user: 'SYSTEM', type: 'Process create', msg: 'services.exe > C:\\Windows\\System32\\svchost.exe -k netsvcs (signed: Microsoft Windows)' },
      { id: 'r13', t: '01:12:00', src: 'process', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'File create', msg: 'vsarchiver.exe wrote D:\\Shares\\Finance\\_archive_manifest_2026-09-26.csv (3,544 entries)' },
      { id: 'r14', t: '01:15:00', src: 'winevt', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'Security 4663', msg: 'An attempt was made to access an object. Object: D:\\Shares\\Finance\\2021\\Q3\\ledger.xlsx.vsarc  Accesses: WriteData  Process: vsarchiver.exe  Account: svc_vaultsync' },
    ],
    key: [
      { id: 'k-change', label: 'Approved change for exactly this job', rows: ['r02'], why: 'CHG-5120 names the host, the tool, the .vsarc stubs, the account and a window that contains the alert.' },
      { id: 'k-signed', label: 'Signed archiver started by services.exe as its service account', rows: ['r04'], why: 'A validly signed, known binary in Program Files, started by the Service Control Manager under svc_vaultsync and seen monthly: not a dropped tool.' },
      { id: 'k-dest', label: 'Data goes to the internal archive server', rows: ['r06', 'r08', 'r09'], why: 'The traffic goes to ARCH-COLD01 (10.10.20.80) over an existing rule, not to the internet. That matches archiving, not exfiltration.' },
      { id: 'k-noprec', label: 'No ransomware precursors', rows: ['r11'], why: 'Ransomware nearly always deletes shadow copies and backups (T1490) and drops ransom notes. None of that happened.' },
    ],
    related: ['r03', 'r05', 'r07', 'r13', 'r14'],
    verdict: 'btp',
    parQueries: 4,
    writeup: [
      { label: 'Cites the change ticket', any: ['chg-5120', 'change', 'approved'] },
      { label: 'Identifies the signed archiver', any: ['vsarchiver', 'vaultsync', 'signed'] },
      { label: 'Notes the internal destination', any: ['arch-cold01', '10.10.20.80', 'internal', 'archive server'] },
      { label: 'Notes the missing ransomware signs', any: ['vssadmin', 'shadow', 'ransom note', 'precursor', 'no ransom'] },
    ],
    explanation:
      'Benign true positive. Thousands of files really were renamed, so the rule worked. But it was the approved CHG-5120 archive job: a validly signed VaultSync binary started by services.exe under its service account, replacing old files with .vsarc stubs and sending the data to the internal archive server. There are no shadow-copy deletions, no ransom notes and no internet traffic.',
    strong: [
      'A critical rule deserves fast, careful checks, not panic: who ran it, what binary, where is the data going, and are the usual ransomware precursors present?',
      'Check for what should be there if it were ransomware (shadow deletion, ransom notes, encryption-sized writes, internet traffic) as well as what is there.',
      'Confirm the change is real: the ticket, the account, the window and the tool all match.',
      'Tune narrowly: exclude vsarchiver.exe (by signer and path) under svc_vaultsync on SRV-FS02 during approved archive windows, not the whole server.',
      'Tell the storage team the job trips the ransomware rule, so future archive windows can be announced to the SOC.',
    ],
  },

  // ------------------------------------------------------------------ L2-4: ambiguous Kerberoasting
  {
    id: 'siem-l2-rc4-tickets',
    tier: 'l2',
    title: 'Forty service tickets in two minutes',
    difficulty: 3,
    ambiguous: true,
    date: 'Thu 24 Sep 2026',
    summary: 'An IT workstation requests RC4 Kerberos tickets for dozens of service accounts. Kerberoasting, or the new inventory tool? The EDR sensor on the host is degraded.',
    requires: { skills: ['l2-siem', 'l2-attack'] },
    alert: {
      id: 'ALRT-5431',
      name: 'Possible Kerberoasting: many RC4 service tickets from one account',
      severity: 'high',
      time: '15:42:30',
      host: 'SRV-DC01',
      user: 'it-omar',
      source: '10.10.9.41 (WS-IT-09)',
      detail: '38 Kerberos service ticket requests (4769) with encryption type 0x17 (RC4) for 38 different service accounts in 2 minutes, all from WS-IT-09.',
    },
    logs: [
      { id: 'k01', t: '09:00:00', src: 'ops', host: 'CHANGE-CAL', user: '', type: 'Change window', msg: 'CHG-5099 (approved): pilot of AssetScope inventory tool, which enumerates service principal names (SPNs) to map services. Pilot host: WS-IT-11. Owner: it-omar. Runs: Thu-Fri, business hours' },
      { id: 'k02', t: '14:10:00', src: 'ops', host: 'EDR', user: '', type: 'Sensor status', msg: 'WS-IT-09 sensor DEGRADED since 14:02 (driver update pending reboot): process and network telemetry not collected. Heartbeat only.' },
      { id: 'k03', t: '15:38:12', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'Security 4624', msg: 'An account was successfully logged on. Account: it-omar  Logon Type: 3  Source: 10.10.9.41 (WS-IT-09)' },
      { id: 'k04', t: '15:40:28', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'LDAP query', msg: 'Directory service query from 10.10.9.41 (it-omar): (&(objectClass=user)(servicePrincipalName=*)) returned 41 accounts' },
      { id: 'k05', t: '15:40:31', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'Security 4769', msg: 'A Kerberos service ticket was requested. Account: it-omar  Service: svc_sql  Ticket Encryption Type: 0x17 (RC4)  Client: 10.10.9.41' },
      { id: 'k06', t: '15:40:32', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'Security 4769', msg: 'A Kerberos service ticket was requested. Account: it-omar  Service: svc_backup  Ticket Encryption Type: 0x17 (RC4)  Client: 10.10.9.41' },
      { id: 'k07', t: '15:40:33', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'Security 4769', msg: 'A Kerberos service ticket was requested. Account: it-omar  Service: svc_vaultsync  Ticket Encryption Type: 0x17 (RC4)  Client: 10.10.9.41' },
      { id: 'k08', t: '15:42:30', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'Security 4769', msg: '...35 more 4769 events from 15:40:34 to 15:42:30 for other service accounts (svc_web, svc_crm, svc_print, ...), all encryption type 0x17, client 10.10.9.41' },
      { id: 'k09', t: '15:30:05', src: 'winevt', host: 'SRV-DC01', user: 'svc_sql', type: 'Security 4769', msg: 'A Kerberos service ticket was requested. Account: SRV-APP01$  Service: svc_sql  Ticket Encryption Type: 0x12 (AES256)  Client: 10.10.30.11' },
      { id: 'k10', t: '15:41:00', src: 'ops', host: 'DIRECTORY', user: '', type: 'Account info', msg: 'it-omar: IT systems administrator, on the AssetScope pilot team. Workstations assigned: WS-IT-09 (daily laptop), WS-IT-11 (pilot VM)' },
      { id: 'k11', t: '15:44:10', src: 'firewall', host: 'FW-CORE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.9.41:51020 -> 10.10.1.11:88 rule=clients-to-dc (Kerberos)' },
      { id: 'k12', t: '15:45:00', src: 'ops', host: 'DIRECTORY', user: '', type: 'Account info', msg: 'Service account password ages: svc_sql 6 years, svc_backup 4 years, svc_vaultsync 3 months. 22 of the 38 accounts still allow RC4.' },
      { id: 'k13', t: '15:50:00', src: 'winevt', host: 'SRV-DC01', user: '', type: 'Search', msg: 'No logons (4624/4768) by any of the 38 service accounts from unusual hosts since 15:40' },
      { id: 'k14', t: '15:52:18', src: 'proxy', host: 'WS-IT-09', user: 'it-omar', type: 'GET 200', msg: 'it-omar WS-IT-09 GET https://docs.assetscope-vendor.example/guides/spn-discovery 200 text/html' },
    ],
    key: [
      { id: 'k-burst', label: '38 RC4 service tickets for 38 accounts in 2 minutes', rows: ['k05', 'k06', 'k07', 'k08'], why: 'Kerberoasting (T1558.003) requests service tickets for many SPN accounts, preferably RC4, and cracks them offline. It is also exactly what an SPN-mapping tool does.' },
      { id: 'k-ldap', label: 'SPN enumeration right before', rows: ['k04'], why: 'An LDAP query for every account with an SPN is the usual first step of both Kerberoasting tools and inventory tools.' },
      { id: 'k-edrgap', label: 'No process telemetry from WS-IT-09', rows: ['k02'], why: 'The one fact that would settle it (which program made the requests) is missing: the sensor is degraded.' },
      { id: 'k-change', label: 'The approved pilot runs on WS-IT-11, not WS-IT-09', rows: ['k01'], why: 'The change covers the tool and the owner, but a different host. A pilot that moved to his laptop is plausible; so is an attacker on his laptop using his account.' },
    ],
    related: ['k03', 'k10', 'k12', 'k13', 'k14'],
    verdict: 'tp',
    defensible: { tp: 1, btp: 0.75 },
    confidence: { low: 0.5, medium: 1, high: 0 },
    parQueries: 4,
    gaps: [
      { id: 'gk-proc', correct: true, text: 'Which program on WS-IT-09 made the requests: the EDR sensor is degraded.', why: 'AssetScope.exe versus Rubeus or a PowerShell script would decide it almost on its own.' },
      { id: 'gk-omar', correct: true, text: 'Whether it-omar was actually running the pilot from his laptop.', why: 'A phone call to omar (not an email or chat) settles whether this was him and whether the pilot moved.' },
      { id: 'gk-crack', correct: true, text: 'Whether the tickets can be cracked: several accounts have old passwords and still allow RC4.', why: 'If this is Kerberoasting, the risk is set by password strength. svc_sql\'s 6-year-old password is the real exposure.' },
      { id: 'gk-4769', correct: false, text: 'Whether the 4769 events really mean service tickets were issued.', why: 'They do: 4769 is logged on the DC when a service ticket is requested and issued. That part is not in doubt.' },
      { id: 'gk-fw', correct: false, text: 'Whether the firewall allowed Kerberos traffic to the DC.', why: 'It did (k11), and it always does for clients. That does not help decide between tool and attacker.' },
      { id: 'gk-none', correct: false, text: 'Nothing: the change ticket covers it.', why: 'The ticket names a different host, and nothing shows which program ran. It supports one story, it does not prove it.' },
    ],
    steps: {
      'verify-user': { rating: 'best', why: 'Call omar on a known number: did he run AssetScope from WS-IT-09 at 15:40? If he did not, it is almost certainly an attack using his account.' },
      'more-logs': { rating: 'best', why: 'Get the missing process data: reboot the sensor, or pull the local Sysmon/4688 events from WS-IT-09.' },
      escalate: { rating: 'best', why: 'Hand it to Tier 2 as possible Kerberoasting, medium confidence, with the EDR gap and the host mismatch stated. Credential theft is time-critical because cracking happens offline.' },
      contain: { rating: 'ok', why: 'Isolating an admin laptop is disruptive but defensible if omar cannot be reached; rotating the weakest service account passwords (svc_sql) is a sensible precaution either way.' },
      'check-edr': { rating: 'ok', why: 'Worth a look, but the sensor is degraded: it will not show the process until it is fixed.' },
      close: { rating: 'bad', why: 'The change ticket names another host and no process is known. Closing leaves a possible credential-theft attack unexamined.' },
      wait: { rating: 'bad', why: 'Kerberoasted tickets are cracked offline, out of sight. By the time the attacker logs in with svc_sql it is too late to prevent.' },
      reimage: { rating: 'bad', why: 'Wiping the laptop destroys the one place the answer lives, and does nothing about tickets that may already be cracked.' },
    },
    writeup: [
      { label: 'Says what cannot be confirmed', any: ['cannot', "can't", 'unable', 'unclear', 'unknown', 'unverified', 'not sure', 'uncertain', 'degraded'] },
      { label: 'Names Kerberoasting', any: ['kerberoast', 't1558', 'service ticket', 'rc4'] },
      { label: 'Notes the host mismatch or the pilot', any: ['ws-it-11', 'assetscope', 'pilot', 'chg-5099'] },
      { label: 'Proposes verifying with omar', any: ['verify', 'confirm', 'call', 'phone', 'ask', 'contact'] },
    ],
    explanation:
      'Genuinely ambiguous. The pattern (SPN enumeration, then RC4 service tickets for 38 accounts) is textbook Kerberoasting, and it is also what AssetScope does. The approved pilot and the vendor docs point to omar testing the tool; the wrong host and the blind EDR sensor keep an attacker on his laptop on the table. The stronger call is a suspected true positive at medium confidence: verify with omar by phone, restore the process telemetry and rotate the weakest service account passwords. Calling it an expected benign true positive is defensible if you insist on verification.',
    strong: [
      'Know what the attack looks like in logs: an LDAP query for SPN accounts, then a burst of 4769 events with encryption type 0x17 from one client.',
      'Separate facts from the story: the ticket requests are facts; "it is the pilot" is an inference the change ticket does not fully support (wrong host).',
      'Find the missing piece: the program that made the requests. Fix the sensor or pull local logs.',
      'Think about impact while you verify: a 6-year-old svc_sql password that still allows RC4 is crackable. Rotating it is cheap.',
      'Long-term fixes either way: strong (25+ character) or managed service account passwords, AES-only Kerberos, and a detection that excludes the approved pilot host only.',
    ],
    arguments: {
      tp: 'SPN enumeration followed by RC4 tickets for every service account is exactly Kerberoasting, from a host the change ticket does not cover, with no process visibility. Treat it as credential theft until proven otherwise.',
      btp: 'The account owner runs an approved pilot of a tool that does precisely this, during its scheduled days, and was reading the vendor\'s SPN discovery guide minutes later. No service account has been used anywhere unusual.',
    },
    settle: [
      'omar confirming by phone that he ran AssetScope from WS-IT-09 (and why not WS-IT-11).',
      'Process telemetry from WS-IT-09 showing which executable requested the tickets.',
      'Any logon by one of the 38 service accounts from an unusual host in the next hours or days.',
    ],
    outcome: {
      title: 'It was the pilot, on the wrong machine',
      verdict: 'btp',
      text: 'omar answered his phone at 16:05: the pilot VM WS-IT-11 had run out of disk, so he ran AssetScope from his laptop. Local logs recovered after the sensor reboot showed AssetScope.exe making the requests. The change was updated, and svc_sql and svc_backup got new long random passwords anyway, because the exercise showed how exposed they were. A careful "suspected true positive, verify" still scored well: at 15:42 nothing in the SIEM could tell the tool from an attacker.',
    },
  },

  // ------------------------------------------------------------------ L2-5: web SQLi
  {
    id: 'siem-l2-sqli-search',
    tier: 'l2',
    title: 'The search box that answered in rows',
    difficulty: 2,
    date: 'Fri 25 Sep 2026',
    summary: 'The WAF flagged a search request on the customer portal. Decide whether this is a probe that bounced, or a query that came back with data.',
    requires: { skills: ['l2-web'] },
    alert: {
      id: 'ALRT-6104',
      name: 'WAF: SQL injection pattern in /search',
      severity: 'high',
      time: '11:14:02',
      host: 'WAF-EDGE',
      user: '',
      source: 'Web application firewall',
      detail: 'A request to portal.corp.example/search contained UNION SELECT. The WAF logged it and did not block (detection-only policy on this path).',
    },
    logs: [
      { id: 'q01', t: '11:02:10', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 200', msg: '203.0.113.77 GET https://portal.corp.example/ 200 text/html  bytes_out=420' },
      { id: 'q02', t: '11:06:40', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 404', msg: '203.0.113.77 GET https://portal.corp.example/wp-admin 404  (no such path on this app)' },
      { id: 'q03', t: '11:11:18', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 200', msg: '203.0.113.77 GET https://portal.corp.example/search?q=acme 200 text/html  bytes_out=8800  time_ms=40' },
      { id: 'q04', t: '11:12:55', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 500', msg: '203.0.113.77 GET https://portal.corp.example/search?q=acme%27 500  time_ms=38  body contains "syntax error near"' },
      { id: 'q05', t: '11:13:40', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 500', msg: '203.0.113.77 GET https://portal.corp.example/search?q=acme%27%20AND%20SLEEP(5)-- 500  time_ms=5120' },
      { id: 'q06', t: '11:14:02', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 200', msg: '203.0.113.77 GET https://portal.corp.example/search?q=acme%27%20UNION%20SELECT%20username,password,email%20FROM%20users-- 200 text/html  bytes_out=64000  time_ms=90' },
      { id: 'q07', t: '11:14:02', src: 'ids', host: 'IDS-EDGE', user: '', type: 'eve alert', msg: 'signature_id=2026101  msg="SQL UNION SELECT in URI"  src_ip=203.0.113.77  dest=portal.corp.example  action=allowed  (rule is alert-only on this span)' },
      { id: 'q08', t: '11:14:40', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 200', msg: '203.0.113.77 GET https://portal.corp.example/search?q=acme%27%20UNION%20SELECT%20card_last4,exp,name%20FROM%20payments-- 200  bytes_out=120000' },
      { id: 'q09', t: '11:20:00', src: 'ops', host: 'APP', user: '', type: 'Deploy note', msg: 'portal.corp.example search still builds SQL by string concat. Parameterised queries are on the backlog (CHG-6001, not started).' },
      { id: 'q10', t: '11:22:15', src: 'proxy', host: 'WAF-EDGE', user: 'nina', type: 'GET 200', msg: '10.10.4.12 (nina, corp laptop) GET https://portal.corp.example/search?q=invoice 200  bytes_out=6400  time_ms=35' },
      { id: 'q11', t: '11:30:00', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 203.0.113.77:44102 -> 203.0.113.10:443  (portal public address) bytes_out=90000' },
      { id: 'q12', t: '11:40:12', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: '10.10.4.12 query A portal.corp.example -> 203.0.113.10' },
    ],
    key: [
      { id: 'k-error', label: 'A quote broke the query, then SLEEP delayed it', rows: ['q04', 'q05'], why: 'A 500 that mentions a syntax error, then a 5-second SLEEP that actually waited 5 seconds, means the database evaluated the attacker\'s SQL. That is past a WAF string match.' },
      { id: 'k-union', label: 'UNION SELECT came back 200 with a large body', rows: ['q06', 'q08'], why: 'Two successful UNION queries, including a payments table, returned tens of kilobytes. The data left. The WAF was in detection-only mode, so action=allowed matches.' },
      { id: 'k-waf', label: 'The control that should have blocked was alert-only', rows: ['q07', 'q09'], why: 'The IDS signature and the app note agree: this path is logged, not blocked, and the query is still concatenated.' },
    ],
    related: ['q03', 'q11'],
    verdict: 'tp',
    parQueries: 4,
    writeup: [
      { label: 'Names the injection', any: ['union', 'sqli', 'sql injection', 'sleep'] },
      { label: 'Says data was returned', any: ['200', 'password', 'payments', 'returned', 'bytes'] },
      { label: 'Notes the WAF did not block', any: ['allowed', 'detection-only', 'did not block', 'alert-only', 'not block'] },
    ],
    explanation:
      'True positive. 203.0.113.77 confirmed the search parameter was in the SQL statement (syntax error, then a SLEEP that took five seconds) and then pulled username and payment columns with UNION SELECT. Both came back HTTP 200. The WAF and the IDS only alerted. nina\'s normal search is unrelated.',
    strong: [
      'A WAF hit is a lead. The status code, the timing and the response size say whether the database ran the payload.',
      'SLEEP(5) that takes about five seconds is stronger than a keyword match: the engine evaluated it.',
      'Detection-only mode means the alert can be a successful attack, not a blocked one. Read action=allowed.',
      'Contain: block 203.0.113.77, take the search parameter off the concatenated query (or disable search), and rotate any credentials that were in the users table. Assume the payments columns were read.',
    ],
  },

  // ------------------------------------------------------------------ L2-6: ambiguous web brute vs scanner
  {
    id: 'siem-l2-dir-brute',
    tier: 'l2',
    title: 'Four hundred misses and one admin page',
    difficulty: 3,
    ambiguous: true,
    date: 'Fri 25 Sep 2026',
    summary: 'Something walked the customer portal\'s paths and got one 200 on /admin. The vulnerability scanner was supposed to run tonight, from a different address.',
    requires: { skills: ['l2-web'] },
    alert: {
      id: 'ALRT-6118',
      name: 'Directory brute force against portal.corp.example',
      severity: 'medium',
      time: '21:16:40',
      host: 'WAF-EDGE',
      user: '',
      source: 'Web application firewall',
      detail: 'More than 400 requests for well-known paths from one external address in six minutes, mostly 404, one 200.',
    },
    logs: [
      { id: 'd01', t: '18:00:00', src: 'ops', host: 'CHANGE-CAL', user: '', type: 'Change window', msg: 'CHG-6188 (approved): nightly authenticated scan of portal.corp.example by scanner host 10.10.50.8, user svc_scan, window 21:00-23:00. External scans are not in this change.' },
      { id: 'd02', t: '21:10:02', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 404', msg: '192.0.2.45 GET https://portal.corp.example/phpmyadmin 404' },
      { id: 'd03', t: '21:10:03', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 404', msg: '192.0.2.45 GET https://portal.corp.example/.env 404' },
      { id: 'd04', t: '21:10:04', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 404', msg: '192.0.2.45 GET https://portal.corp.example/server-status 404' },
      { id: 'd05', t: '21:12:20', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 401', msg: '192.0.2.45 GET https://portal.corp.example/admin 401  WWW-Authenticate: Basic' },
      { id: 'd06', t: '21:14:11', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 401', msg: '192.0.2.45 GET https://portal.corp.example/admin 401  (second try, different Authorization header, still rejected)' },
      { id: 'd07', t: '21:16:40', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 200', msg: '192.0.2.45 GET https://portal.corp.example/admin/health 200 text/plain  body="ok"  (no cookie, no Authorization on this path)' },
      { id: 'd08', t: '21:18:00', src: 'ops', host: 'SCANNER', user: 'svc_scan', type: 'Scanner status', msg: '10.10.50.8 scan of portal.corp.example has not started. Last heartbeat 20:40. Queue delay, owner paged.' },
      { id: 'd09', t: '21:19:12', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 192.0.2.45:51002 -> 203.0.113.10:443' },
      { id: 'd10', t: '21:19:40', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'No traffic from 10.10.50.8 to 203.0.113.10 between 21:00 and 21:19' },
      { id: 'd11', t: '21:22:05', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'POST 401', msg: '192.0.2.45 POST https://portal.corp.example/admin/login 401  (body not logged)' },
      { id: 'd12', t: '21:25:00', src: 'ids', host: 'IDS-EDGE', user: '', type: 'eve alert', msg: 'signature_id=2026440  msg="Directory wordlist against web root"  src_ip=192.0.2.45  action=allowed  count=400 in 6 minutes' },
    ],
    key: [
      { id: 'k-walk', label: 'Hundreds of sensitive paths from an external address', rows: ['d02', 'd03', 'd04', 'd12'], why: 'phpmyadmin, .env and server-status from one external IP is a wordlist, not a user browsing.' },
      { id: 'k-health', label: 'The only 200 is an unauthenticated health page', rows: ['d07'], why: '/admin/health returned "ok" with no credentials. That is a real finding about the app, and it is not proof the admin panel was entered. The login POST stayed 401.' },
      { id: 'k-scanner', label: 'The approved scanner never left 10.10.50.8', rows: ['d01', 'd08', 'd10'], why: 'The change names a different source, and that source has not started. 192.0.2.45 is not the scanner. A delayed job does not explain this IP.' },
    ],
    related: ['d05', 'd06', 'd09', 'd11'],
    verdict: 'tp',
    defensible: { tp: 1, btp: 0.75 },
    confidence: { low: 0.5, medium: 1, high: 0 },
    parQueries: 4,
    gaps: [
      { id: 'gd-who', correct: true, text: 'Who owns 192.0.2.45: a contractor, a missed scanner NAT, or an outsider.', why: 'The change does not name it. Ownership would separate a forgotten external scanner from an attack.' },
      { id: 'gd-body', correct: true, text: 'What /admin/health exposes, and whether any later request was authenticated.', why: 'The body is the word ok. You cannot see whether a session appeared after the log ends.' },
      { id: 'gd-login', correct: false, text: 'Whether the login POST succeeded.', why: 'It did not: the status is 401. That part is in the log.' },
      { id: 'gd-chg', correct: false, text: 'Whether any scan was approved tonight.', why: 'CHG-6188 is approved. The open question is whether this IP is that scan, and the scanner status says it is not.' },
    ],
    steps: {
      'more-logs': { rating: 'best', why: 'Pull the next hour of access logs and the app\'s auth log. A session cookie after 21:16 would change this from reconnaissance to access.' },
      'verify-user': { rating: 'best', why: 'Ask the scan owner whether any external runner, including a NAT you do not have written down, uses 192.0.2.45.' },
      escalate: { rating: 'best', why: 'Hand it over as external reconnaissance that touched an open health URL, medium confidence, with the scanner mismatch stated.' },
      contain: { rating: 'ok', why: 'Blocking 192.0.2.45 at the edge is reversible and does not depend on knowing the owner. Do not take the portal down for a 401.' },
      'check-edr': { rating: 'ok', why: 'The portal host is a server. EDR will not explain an external wordlist, but it will show whether a web shell landed. Worth a look, not the first question.' },
      close: { rating: 'bad', why: 'The approved scanner is a different address and has not started. Closing treats an external wordlist as the change ticket.' },
      wait: { rating: 'bad', why: 'Waiting does not answer whether a session appears, and the health endpoint is already exposed.' },
      reimage: { rating: 'bad', why: 'Nothing shows code execution on the server. Reimaging the portal destroys a production app to answer a source-IP question.' },
    },
    writeup: [
      { label: 'Says what is not proven', any: ['cannot', "can't", 'not proven', 'unclear', 'unknown', 'unverified'] },
      { label: 'Names the wordlist or the paths', any: ['404', 'wordlist', 'phpmyadmin', '.env', 'brute'] },
      { label: 'Notes the scanner mismatch', any: ['10.10.50.8', 'scanner', 'chg-6188', 'not the scanner'] },
      { label: 'Mentions the health page or the failed login', any: ['health', '401', 'admin'] },
    ],
    explanation:
      'Ambiguous, but the stronger call is a true positive at medium confidence. An external address walked sensitive paths and found an unauthenticated health URL. The approved scanner is 10.10.50.8 and it had not started, so "it is the scan" is a hope, not a reading of d08. No login succeeded. A benign true positive is defensible only if you are explicitly waiting on the scan owner to claim 192.0.2.45, and you say so.',
    strong: [
      'Compare the source in the ticket with the source in the log before you reuse the word "approved".',
      'Separate reconnaissance (404 wordlist) from access (a 200 that still has no credentials, a 401 that stayed a 401).',
      'The health endpoint is a real bug even if the rest is a scan. File it. Do not let it decide the verdict by itself.',
      'Grade the reasoning: what you cannot know is who owns the IP and whether a session appeared later.',
    ],
    arguments: {
      tp: 'The change names 10.10.50.8, that host never connected, and 192.0.2.45 walked phpmyadmin and .env from the internet. Treat it as external reconnaissance until someone claims the address.',
      btp: 'A scan was approved for this exact host and window, the scanner queue is delayed, and nothing authenticated. An external runner that was left out of the ticket is possible, so a benign call is arguable if you are verifying the address rather than ignoring it.',
    },
    settle: [
      'The scan owner confirming whether any runner uses 192.0.2.45.',
      'Access logs after 21:25 showing either a session or continued 401s.',
      'A packet or proxy capture of the Authorization headers, which this alert does not include.',
    ],
    outcome: {
      title: 'It was not the scanner',
      verdict: 'tp',
      text: 'The scan owner confirmed at 22:10 that 10.10.50.8 was stuck in the queue and that 192.0.2.45 is not theirs. The address was an external wordlist. /admin/health was unauthenticated on purpose and got a ticket of its own. No admin session appeared. Blocking the IP and filing the health page was the right containment. Calling it the approved scan was the mistake the change ticket was there to prevent.',
    },
  },

  // ------------------------------------------------------------------ L2-7: cloud AiTM
  {
    id: 'siem-l2-aitm-session',
    tier: 'l2',
    title: 'MFA succeeded, then the mailbox moved',
    difficulty: 3,
    date: 'Mon 28 Sep 2026',
    summary: 'Entra shows a clean MFA success for a finance user, then mail is read from a second address. Decide whether the second row is still the user.',
    requires: { skills: ['l2-saas'] },
    alert: {
      id: 'ALRT-6220',
      name: 'Impossible travel plus a new inbox rule',
      severity: 'high',
      time: '16:22:18',
      host: 'IDP',
      user: 'priya',
      source: 'Entra ID Protection',
      detail: 'priya@corp.example satisfied MFA, then a forwarding rule was created from a different IP within ten minutes.',
    },
    logs: [
      { id: 'a01', t: '16:11:02', src: 'idp', host: 'IDP', user: 'priya', type: 'Sign-in success', msg: 'priya@corp.example errorCode=0 MFA satisfied (Phone App Notification) ip=198.51.100.15 device=Priya-Laptop compliant app=Office' },
      { id: 'a02', t: '16:11:40', src: 'idp', host: 'IDP', user: 'priya', type: 'Sign-in failure', msg: 'priya@corp.example errorCode=500121 MFA prompt not completed ip=203.0.113.40 device=empty' },
      { id: 'a03', t: '16:14:05', src: 'idp', host: 'IDP', user: 'priya', type: 'Sign-in success', msg: 'priya@corp.example errorCode=0 MFA previously satisfied ip=203.0.113.40 device=empty UA=Chrome/120 session=9c2 (same session as 16:11:02)' },
      { id: 'a04', t: '16:16:20', src: 'cloud', host: 'EXO', user: 'priya', type: 'MailItemsAccessed', msg: 'MailItemsAccessed MailAccessType=Sync ClientIP=203.0.113.40 SessionId=9c2 count=860' },
      { id: 'a05', t: '16:18:44', src: 'cloud', host: 'EXO', user: 'priya', type: 'New-InboxRule', msg: 'New-InboxRule Name=RSS RedirectTo=inbox@mail.example MarkAsRead=True ClientIP=203.0.113.40' },
      { id: 'a06', t: '16:20:01', src: 'idp', host: 'IDP', user: 'priya', type: 'Consent to application', msg: 'Consent to application by priya@corp.example app="Invoice Helper" publisher=invoice-helper.example scopes=Mail.Read,offline_access adminConsent=no ip=203.0.113.40' },
      { id: 'a07', t: '16:22:18', src: 'idp', host: 'IDP', user: 'priya', type: 'Risk', msg: 'Risk detection: impossible travel and unfamiliar IP 203.0.113.40. No Conditional Access policy blocked the token (no 53003).' },
      { id: 'a08', t: '16:30:00', src: 'idp', host: 'IDP', user: 'priya', type: 'Sign-in success', msg: 'priya@corp.example errorCode=0 MFA satisfied ip=198.51.100.15 device=Priya-Laptop app=Office' },
      { id: 'a09', t: '16:31:12', src: 'ops', host: 'CA-POLICY', user: '', type: 'Policy', msg: 'Finance users: MFA required. Phishing-resistant MFA is not required. Session revoke is a manual admin action. Continuous access evaluation is on for Exchange only.' },
      { id: 'a10', t: '16:40:00', src: 'cloud', host: 'EXO', user: 'priya', type: 'MailItemsAccessed', msg: 'MailItemsAccessed MailAccessType=Bind ClientIP=198.51.100.15 SessionId=9c1 count=3 (her laptop)' },
      { id: 'a11', t: '15:00:00', src: 'idp', host: 'IDP', user: 'priya', type: 'Sign-in failure', msg: 'priya@corp.example errorCode=50126 invalid password ip=198.51.100.15 device=Priya-Laptop (one typo at lunch)' },
      { id: 'a12', t: '16:45:22', src: 'email', host: 'MAIL-GW', user: 'priya', type: 'Delivered', msg: 'To priya@corp.example From: "Shared file" <files@invoice-helper.example> Subject: "Invoice for your review" URL https://invoice-helper.example/doc' },
    ],
    key: [
      { id: 'k-replay', label: 'Same session reused from a second IP with no new MFA', rows: ['a01', 'a03'], why: 'The laptop completed MFA. Minutes later session 9c2 is presented from 203.0.113.40 with an empty device and "MFA previously satisfied". That is session replay after a proxy (T1557, T1550.004), not a second password entry.' },
      { id: 'k-mail', label: 'Mail was read and a forward rule was created from that IP', rows: ['a04', 'a05'], why: 'Sync of 860 items and a RedirectTo rule with MarkAsRead means the session was used to collect mail and to hide the replies (T1114).' },
      { id: 'k-consent', label: 'An unverified app was granted Mail.Read and offline_access', rows: ['a06'], why: 'User consent is enough. offline_access keeps a refresh token after a password change until the grant and the sessions are revoked (T1528).' },
    ],
    related: ['a02', 'a07', 'a09', 'a12'],
    verdict: 'tp',
    parQueries: 4,
    writeup: [
      { label: 'Describes the second IP or the replay', any: ['203.0.113.40', 'session', 'replay', 'proxy', 'aitm'] },
      { label: 'Mentions the inbox rule or the mail read', any: ['inbox rule', 'redirect', 'mailitemsaccessed', 'forward'] },
      { label: 'Mentions the app consent', any: ['consent', 'oauth', 'offline_access', 'invoice helper'] },
      { label: 'Says a password reset is not enough', any: ['revoke', 'session', 'grant'] },
    ],
    explanation:
      'True positive: adversary-in-the-middle. Priya completed a real MFA prompt on her laptop. The same session was then used from 203.0.113.40 to sync mail, create a forwarding rule, and consent an app to Mail.Read with offline_access. 50126 at lunch is a typo. Her later laptop sign-in is her. Containment is revoke sessions, reset the password, remove the rule and remove the grant. CAE on Exchange does not cover the app token by itself.',
    strong: [
      'MFA satisfied on the first row is how a proxy gets the cookie. Compare device, user agent and session id on the next row.',
      '500121 on the proxy IP is the prompt the user did not complete there. It is not a bad password (50126).',
      'Revoke sessions and the OAuth grant together. A password reset leaves both alive.',
      'There was no 53003. The risk detection fired and no policy blocked the token. That is a gap to file, not a reason to close.',
    ],
  },

  // ------------------------------------------------------------------ L2-8: ambiguous impossible travel
  {
    id: 'siem-l2-vpn-travel',
    tier: 'l2',
    title: 'Two cities, one laptop',
    difficulty: 2,
    ambiguous: true,
    date: 'Tue 29 Sep 2026',
    summary: 'Impossible travel fired for a developer. One address is the office ISP, the other is in the company VPN range, and the device id is missing on the VPN row.',
    requires: { skills: ['l2-saas'] },
    alert: {
      id: 'ALRT-6302',
      name: 'Impossible travel: two cities in eight minutes',
      severity: 'medium',
      time: '08:22:10',
      host: 'IDP',
      user: 'devon',
      source: 'Entra ID Protection',
      detail: 'devon@corp.example signed in from Example City and Other City eight minutes apart.',
    },
    logs: [
      { id: 't01', t: '08:14:02', src: 'idp', host: 'IDP', user: 'devon', type: 'Sign-in success', msg: 'devon@corp.example errorCode=0 MFA satisfied ip=198.51.100.15 city=Example City ASN=Example Cable device=Devon-Laptop compliant UA=Edge' },
      { id: 't02', t: '08:22:10', src: 'idp', host: 'IDP', user: 'devon', type: 'Sign-in success', msg: 'devon@corp.example errorCode=0 MFA satisfied ip=192.0.2.80 city=Other City ASN=Corp VPN device=empty UA=Edge session=new' },
      { id: 't03', t: '08:22:40', src: 'idp', host: 'IDP', user: 'devon', type: 'Risk', msg: 'Impossible travel. Conditional Access did not block (no 53003). Both applications: Office.' },
      { id: 't04', t: '08:00:00', src: 'ops', host: 'NET-DOC', user: '', type: 'VPN range', msg: 'Documented corp VPN egress: 192.0.2.80/28, ASN Corp VPN. Browser sign-ins through the VPN client often have an empty device id even when the laptop is compliant. Owner of the range: network team.' },
      { id: 't05', t: '08:23:10', src: 'cloud', host: 'EXO', user: 'devon', type: 'MailItemsAccessed', msg: 'MailItemsAccessed MailAccessType=Bind ClientIP=192.0.2.80 count=4 (inbox, last few minutes)' },
      { id: 't06', t: '08:30:00', src: 'cloud', host: 'EXO', user: 'devon', type: 'Audit search', msg: 'No New-InboxRule, no Set-Mailbox forwarding, no Consent to application for devon in the last 7 days.' },
      { id: 't07', t: '08:31:00', src: 'idp', host: 'IDP', user: 'devon', type: 'Sign-in failure', msg: 'No 50126, 500121 or 50074 for devon since yesterday. No unfamiliar user agent.' },
      { id: 't08', t: '07:50:00', src: 'ops', host: 'DIRECTORY', user: '', type: 'Account info', msg: 'devon: software engineer, works from home three days a week, uses the corp VPN for source control. Laptop Devon-Laptop is compliant as of yesterday.' },
      { id: 't09', t: '08:40:12', src: 'proxy', host: 'PROXY', user: 'devon', type: 'CONNECT', msg: 'Devon-Laptop (10.10.8.20) CONNECT git.corp.example:443 via corp proxy, user devon' },
      { id: 't10', t: '08:41:00', src: 'firewall', host: 'FW-VPN', user: '', type: 'ASSIGN', msg: 'VPN session for user devon assigned 192.0.2.80 from 08:21:50, client cert matches Devon-Laptop' },
      { id: 't11', t: '08:10:00', src: 'idp', host: 'IDP', user: 'sam', type: 'Sign-in success', msg: 'sam@corp.example errorCode=0 ip=198.51.100.15 device=Sam-Laptop (same cable ASN, different user, normal morning)' },
    ],
    key: [
      { id: 'k-vpn', label: 'The second IP is the documented VPN, and a session was assigned', rows: ['t04', 't10'], why: '192.0.2.80 is in the written VPN egress, and the concentrator assigned it to devon at 08:21 with the laptop\'s client certificate. That is a better explanation than a second person in Other City.' },
      { id: 'k-device', label: 'The Entra row omitted the device id', rows: ['t02'], why: 'An empty device on a VPN browser sign-in is a known gap in the ops note. It is also what a stolen session looks like, so it cannot close the case by itself.' },
      { id: 'k-quiet', label: 'No mailbox rule, no consent, no failed MFA', rows: ['t06', 't07'], why: 'Follow-on collection is absent. Absence is not proof, and it is why this is not the payroll case.' },
    ],
    related: ['t01', 't05', 't08', 't09'],
    verdict: 'btp',
    defensible: { btp: 1, tp: 0.75 },
    confidence: { low: 0.5, medium: 1, high: 0 },
    parQueries: 4,
    gaps: [
      { id: 'gt-user', correct: true, text: 'Whether devon actually opened the VPN, which only devon or the concentrator log can confirm.', why: 'The assignment log is strong, and a phone call removes the remaining chance of a stolen client certificate.' },
      { id: 'gt-device', correct: true, text: 'Why Entra left the device blank on the VPN sign-in.', why: 'The ops note says this happens. You have not proven it happened this time rather than a session with no device.' },
      { id: 'gt-geo', correct: false, text: 'Whether the two cities are physically eight minutes apart.', why: 'They are not. The question is whether the second geo is the VPN egress, which the range document answers.' },
      { id: 'gt-sam', correct: false, text: 'Whether sam sharing the cable ASN means the account is shared.', why: 'sam is a different user on the same ISP. That is normal and does not touch devon.' },
    ],
    steps: {
      'verify-user': { rating: 'best', why: 'Call devon. Did you connect the VPN around 08:21? A yes, plus the concentrator log, settles it.' },
      'more-logs': { rating: 'ok', why: 'You already have the concentrator assignment. More mail logs are optional unless the call contradicts the certificate.' },
      escalate: { rating: 'ok', why: 'Reasonable if devon does not answer. Say medium confidence, VPN range matches, device id missing, no follow-on.' },
      contain: { rating: 'bad', why: 'Revoking or disabling on a documented VPN egress, with a matching client certificate, locks out someone who is working. Wait for the call.' },
      'check-edr': { rating: 'ok', why: 'Confirm Devon-Laptop is online and compliant. It will not explain the Entra device gap.' },
      close: { rating: 'bad', why: 'Closing with no user check ignores the blank device. The VPN document makes a benign call likely, not finished.' },
      wait: { rating: 'ok', why: 'A short wait while you dial devon is fine. Do not leave it for the next shift with no owner.' },
      reimage: { rating: 'bad', why: 'Nothing on the laptop looks hostile. Wiping it destroys the machine that just presented a valid client certificate.' },
    },
    writeup: [
      { label: 'Says the VPN is the likely cause and what is still open', any: ['vpn', '192.0.2.80', 'cannot', 'unclear', 'unconfirmed', 'not sure'] },
      { label: 'Mentions the blank device', any: ['device', 'empty', 'blank'] },
      { label: 'Notes the lack of follow-on', any: ['no rule', 'no consent', 'no forward', 'inbox'] },
      { label: 'Wants the user or the concentrator', any: ['call', 'verify', 'devon', 'certificate', 'concentrator'] },
    ],
    explanation:
      'Ambiguous only at the edges. The stronger call is a benign true positive at medium confidence: the second address is the documented VPN, the concentrator assigned it to devon with the laptop certificate, and nothing collected mail or consented an app. A true positive is defensible if you weigh the blank device more heavily than the certificate and you are still verifying. High confidence either way is wrong until devon or the certificate check is done.',
    strong: [
      'Impossible travel is a geo comparison. VPN egress, carrier NAT and a bad city on an anycast address all create it.',
      'Read the network document before you disable the user. 192.0.2.80 was already written down.',
      'A blank device is a reason to ask, not a reason to skip the ASN.',
      'Do not auto-disable this alert. The false positive cost is a locked-out engineer, and the true positive signs (rule, consent, new user agent) are absent.',
    ],
    arguments: {
      btp: 'The IP is in the documented VPN range, the concentrator tied it to devon\'s client certificate one minute earlier, the user agent matches, and there is no rule or consent. Travel here is the geo of the concentrator.',
      tp: 'Entra recorded a new session with an empty device from a city the user was not in eight minutes earlier, and no policy blocked it. Until devon confirms the VPN click, a stolen laptop certificate is still on the table.',
    },
    settle: [
      'devon confirming the VPN connection at 08:21.',
      'The client certificate serial on the concentrator matching Devon-Laptop\'s current certificate, which t10 already summarises.',
      'Any inbox rule or consent in the hours after the alert.',
    ],
    outcome: {
      title: 'He was on the VPN',
      verdict: 'btp',
      text: 'devon answered: he connected the VPN to reach git just after 08:21, from the same laptop. The blank device is the VPN browser gap the network note describes. No rule appeared later. Disabling him would have been the false positive this detection is known for. Asking him, and reading the concentrator line, was the whole case.',
    },
  },

  // ------------------------------------------------------------------ L2-9: KEV on an internet-facing server
  {
    id: 'siem-l2-kev-edge',
    tier: 'l2',
    title: 'The portal patch that was still a ticket',
    difficulty: 2,
    date: 'Wed 30 Sep 2026',
    summary: 'A critical finding on the internet-facing portal is on the team\'s KEV mirror, and tonight someone started requesting the exploit path.',
    requires: { skills: ['l2-vuln'] },
    alert: {
      id: 'ALRT-6408',
      name: 'KEV vulnerability on an internet-facing host with exploit traffic',
      severity: 'high',
      time: '19:12:06',
      host: 'SRV-WEB-02',
      user: '',
      source: 'Vuln scanner + IDS',
      detail: 'CVE-2026-41001 on portal.corp.example is listed in the fictional KEV mirror. An external address requested the known path.',
    },
    logs: [
      { id: 'v01', t: '02:10:00', src: 'ops', host: 'SCANNER', user: 'svc_scan', type: 'Finding', msg: 'Credentialed scan of SRV-WEB-02 (203.0.113.10, internet-facing). CVE-2026-41001, CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H = 9.8, package portal-http 2.4.1, fix in 2.4.8. EPSS 0.94. On the team KEV mirror as of yesterday. Asset: customer portal, critical.' },
      { id: 'v02', t: '09:00:00', src: 'ops', host: 'CHANGE-CAL', user: '', type: 'Exception', msg: 'No exception on file for CVE-2026-41001. Patch window for SRV-WEB-02 was last Sunday. Ticket VULN-441 is open, unassigned, SLA 48 hours, clock started yesterday.' },
      { id: 'v03', t: '18:40:12', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 404', msg: '198.51.100.23 GET https://portal.corp.example/static/logo.png 404' },
      { id: 'v04', t: '19:11:58', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 200', msg: '198.51.100.23 GET https://portal.corp.example/api/export?template=../../../../etc/passwd 200 text/plain  bytes_out=1800' },
      { id: 'v05', t: '19:12:06', src: 'ids', host: 'IDS-EDGE', user: '', type: 'eve alert', msg: 'signature_id=2026410  msg="CVE-2026-41001 path traversal in portal-http"  src_ip=198.51.100.23  dest=203.0.113.10  action=allowed' },
      { id: 'v06', t: '19:12:40', src: 'proxy', host: 'WAF-EDGE', user: '', type: 'GET 200', msg: '198.51.100.23 GET https://portal.corp.example/api/export?template=../../../../etc/shadow 200  bytes_out=2400' },
      { id: 'v07', t: '19:20:00', src: 'ops', host: 'PKG', user: '', type: 'Package', msg: 'SRV-WEB-02 still reports portal-http 2.4.1. 2.4.8 is in the internal repo. No compensating control (the WAF rule for this CVE is in report-only).' },
      { id: 'v08', t: '19:22:15', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 198.51.100.23:41820 -> 203.0.113.10:443' },
      { id: 'v09', t: '19:30:00', src: 'proxy', host: 'WAF-EDGE', user: 'nina', type: 'GET 200', msg: '10.10.4.12 GET https://portal.corp.example/ 200 (nina, normal)' },
      { id: 'v10', t: '12:00:00', src: 'ops', host: 'SCANNER', user: '', type: 'Finding', msg: 'Same CVE also open on SRV-INT-09 (10.10.30.19), not internet-facing, EPSS 0.94, no external hits. Lower priority than SRV-WEB-02.' },
      { id: 'v11', t: '19:40:33', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'No internal host queried a new domain in this window. The requests arrived already addressed to 203.0.113.10.' },
      { id: 'v12', t: '19:45:00', src: 'ids', host: 'IDS-EDGE', user: '', type: 'eve alert', msg: 'Same signature from 198.51.100.23 repeated 6 times between 19:12 and 19:44, all action=allowed' },
    ],
    key: [
      { id: 'k-kev', label: 'Internet-facing, CVSS 9.8, on the KEV mirror, no exception', rows: ['v01', 'v02'], why: 'Known exploited, no authentication required, on the customer portal, and the patch window was missed. Exposure plus KEV outranks a low-EPSS finding on an internal host.' },
      { id: 'k-exploit', label: 'The traversal path returned file contents', rows: ['v04', 'v05', 'v06'], why: 'The IDS named the CVE and the proxy shows HTTP 200 with a body for /etc/passwd and /etc/shadow. This is not a scan that bounced.' },
      { id: 'k-nocontrol', label: 'The package is unpatched and the WAF rule is report-only', rows: ['v07'], why: 'A compensating control that only reports does not stop the next request. The fix version is already in the repo.' },
    ],
    related: ['v08', 'v10', 'v12'],
    verdict: 'tp',
    parQueries: 4,
    writeup: [
      { label: 'Names the CVE or the KEV listing', any: ['cve-2026-41001', 'kev', '9.8'] },
      { label: 'Says the exploit returned data', any: ['passwd', '200', 'traversal', 'shadow', 'export'] },
      { label: 'Notes the missing patch or report-only WAF', any: ['unpatched', '2.4.1', 'report-only', 'no exception', 'not patched'] },
    ],
    explanation:
      'True positive. CVE-2026-41001 is a fictional critical (CVSS 9.8, network, no privileges) on the internet-facing portal, listed on the team KEV mirror, with no exception and a missed patch window. 198.51.100.23 then requested the traversal and got file contents back because the WAF rule is report-only. Patch SRV-WEB-02 first. The same CVE on the internal host is real and is not this incident.',
    strong: [
      'Prioritise by what is true together: internet-facing, no auth, KEV, and traffic that already succeeded. A high CVSS on a closed host is a different queue.',
      'An exception needs an owner and an expiry. "Ticket open" is not a compensating control.',
      'Report-only is how a signature and a breach coexist. Say that in the write-up.',
      'Contain: block 198.51.100.23, turn the WAF rule to block or take the export route offline, patch to 2.4.8, and treat the returned password file as exposed.',
    ],
  },

  // ------------------------------------------------------------------ L2-10: backport, benign true positive
  {
    id: 'siem-l2-backport',
    tier: 'l2',
    title: 'The version number that lied',
    difficulty: 2,
    date: 'Thu 1 Oct 2026',
    summary: 'The scanner says an internal build server is missing a critical openssl patch. The package owner says the fix was backported and the version string did not move.',
    requires: { skills: ['l2-vuln'] },
    alert: {
      id: 'ALRT-6511',
      name: 'Critical openssl finding on SRV-BUILD-04',
      severity: 'high',
      time: '10:05:00',
      host: 'SRV-BUILD-04',
      user: '',
      source: 'Vuln scanner',
      detail: 'Unauthenticated scan reports openssl 3.0.2 against CVE-2026-41088, CVSS 9.8. The host is internal.',
    },
    logs: [
      { id: 'b01', t: '10:00:12', src: 'ops', host: 'SCANNER', user: 'svc_scan', type: 'Finding', msg: 'Unauthenticated scan of SRV-BUILD-04 (10.10.40.14). Banner: openssl 3.0.2. Mapped to CVE-2026-41088, CVSS 9.8. EPSS 0.61. Not on the KEV mirror. No credentialed package list was collected (auth failed).' },
      { id: 'b02', t: '10:05:00', src: 'ops', host: 'PKG', user: '', type: 'Changelog', msg: 'Internal package openssl-corp 3.0.2-corp4 changelog: "backported the CVE-2026-41088 fix from 3.0.13. Upstream version string unchanged, on purpose, so build scripts keep matching." Built 12 Sep. Installed on SRV-BUILD-04 the same day.' },
      { id: 'b03', t: '10:06:20', src: 'ops', host: 'PKG', user: '', type: 'File hash', msg: 'libssl on SRV-BUILD-04 matches the corp4 build hash published with that changelog. It does not match upstream 3.0.2.' },
      { id: 'b04', t: '10:10:00', src: 'firewall', host: 'FW-CORE', user: '', type: 'Search', msg: 'No inbound internet path to 10.10.40.14:443. The host is build-net only.' },
      { id: 'b05', t: '10:12:18', src: 'ids', host: 'IDS-CORE', user: '', type: 'Search', msg: 'No signature hits for CVE-2026-41088 toward 10.10.40.14 in the last 14 days.' },
      { id: 'b06', t: '10:14:00', src: 'ops', host: 'SCANNER', user: '', type: 'Scan auth', msg: 'Credentialed scan of SRV-BUILD-04 failed: svc_scan key not on the host. Banner match is the whole finding.' },
      { id: 'b07', t: '09:40:00', src: 'proxy', host: 'PROXY', user: 'ravi', type: 'GET 200', msg: 'ravi GET https://docs.openssl.example/news/cve-2026-41088 200 (reading the advisory)' },
      { id: 'b08', t: '10:20:33', src: 'process', host: 'SRV-BUILD-04', user: 'builder', type: 'Process create', msg: 'sshd > git (normal build job, signed internal runner)' },
      { id: 'b09', t: '10:22:00', src: 'ops', host: 'CHANGE-CAL', user: '', type: 'Note', msg: 'Platform team asked the SOC last month to expect openssl banner findings on corp4 until the scanner has a backport exception. Exception text was never entered.' },
      { id: 'b10', t: '10:30:00', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'SRV-BUILD-04 query A archive.corp.example -> 10.10.20.80 (the internal archive, daily)' },
      { id: 'b11', t: '11:00:00', src: 'firewall', host: 'FW-EDGE', user: '', type: 'DENY', msg: 'DENY TCP 203.0.113.50:4000 -> 10.10.40.14:443 rule=default-deny (unsolicited, one packet, not related to the banner)' },
    ],
    key: [
      { id: 'k-banner', label: 'The scanner only saw a version string', rows: ['b01', 'b06'], why: 'The auth failed, so the finding is a banner. Banners do not show backports. CVSS 9.8 here is the upstream score, not a measurement of this host.' },
      { id: 'k-back', label: 'The installed library is the backported build', rows: ['b02', 'b03'], why: 'The changelog names this CVE and the file hash matches corp4, not upstream 3.0.2. The version string was left alone so build scripts would not break.' },
      { id: 'k-exposure', label: 'The host is not reachable from the internet and has no exploit hits', rows: ['b04', 'b05'], why: 'Even a real bug here would be a different priority. Combined with the backport, there is nothing to patch tonight.' },
    ],
    related: ['b09', 'b11'],
    verdict: 'btp',
    parQueries: 4,
    writeup: [
      { label: 'Names the backport or the hash', any: ['backport', 'corp4', 'hash', 'changelog'] },
      { label: 'Says the scanner was banner-only', any: ['banner', 'unauth', 'credential', 'version string'] },
      { label: 'Notes where the host sits', any: ['internal', 'not internet', 'no path', 'build'] },
    ],
    explanation:
      'Benign true positive. The scanner correctly noticed a version string that upstream marks as vulnerable, and it stopped there because the credentialed scan failed. The installed libssl is the internal corp4 build, which backported CVE-2026-41088 without moving the version. The host is not internet-facing and has no exploit traffic. File the missing scanner exception so this does not page again. Do not treat the one denied packet as an intrusion.',
    strong: [
      'A version banner is not a package. Backports keep the version and ship the fix. Check the changelog and the file hash.',
      'CVSS on the advisory is the upstream worst case. It does not know about your build.',
      'An exception that was "asked for" and never entered will page you every week. Write it, with an expiry, after you have verified the hash.',
      'This is not a false positive in the narrow sense: the banner really is 3.0.2. The activity the score describes, a vulnerable library, is not what is installed. Benign true positive fits.',
    ],
  },

  // ------------------------------------------------------------------ L2-11: IDS-led
  {
    id: 'siem-l2-ids-beacon',
    tier: 'l2',
    title: 'The signature that was allowed',
    difficulty: 2,
    date: 'Thu 1 Oct 2026',
    summary: 'An IDS signature fired on outbound traffic from a lab workstation and the action was allowed. Use the Zeek conn log to see whether anything actually connected.',
    requires: { skills: ['l2-ids'] },
    alert: {
      id: 'ALRT-6604',
      name: 'ET MALWARE outbound beacon (allowed)',
      severity: 'high',
      time: '13:06:11',
      host: 'IDS-EDGE',
      user: 'lina',
      source: 'Suricata',
      detail: 'Signature 2026770 fired on traffic from WS-LAB-02 to 198.51.100.23:443. The rule action was allowed.',
    },
    logs: [
      { id: 'i01', t: '13:05:40', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'WS-LAB-02 (10.10.12.22) query A cdn.stats-telemetry.example -> 198.51.100.23' },
      { id: 'i02', t: '13:05:58', src: 'ids', host: 'IDS-EDGE', user: '', type: 'Zeek conn', msg: 'uid=C1  id.orig_h=10.10.12.22  id.resp_h=198.51.100.23  id.resp_p=443  proto=tcp  conn_state=sf  orig_bytes=412  resp_bytes=96  duration=1.1' },
      { id: 'i03', t: '13:06:11', src: 'ids', host: 'IDS-EDGE', user: '', type: 'eve alert', msg: 'signature_id=2026770  signature="ET MALWARE ExampleBeacon POST /gate.php"  src_ip=10.10.12.22  dest_ip=198.51.100.23  dest_port=443  alert.action=allowed  flow_id matches uid C1' },
      { id: 'i04', t: '13:07:05', src: 'ids', host: 'IDS-EDGE', user: '', type: 'Zeek conn', msg: 'uid=C2  id.orig_h=10.10.12.22  id.resp_h=198.51.100.23  id.resp_p=443  conn_state=sf  orig_bytes=412  resp_bytes=96' },
      { id: 'i05', t: '13:08:04', src: 'ids', host: 'IDS-EDGE', user: '', type: 'Zeek conn', msg: 'uid=C3  id.orig_h=10.10.12.22  id.resp_h=198.51.100.23  id.resp_p=443  conn_state=sf  orig_bytes=412  resp_bytes=96' },
      { id: 'i06', t: '13:09:20', src: 'ids', host: 'IDS-EDGE', user: '', type: 'Zeek conn', msg: 'uid=C4  id.orig_h=10.10.12.22  id.resp_h=203.0.113.9  id.resp_p=443  conn_state=s0  orig_bytes=0  resp_bytes=0  (SYN, no handshake)' },
      { id: 'i07', t: '13:04:10', src: 'process', host: 'WS-LAB-02', user: 'lina', type: 'Process create', msg: 'explorer.exe > rundll32.exe C:\\Users\\lina\\AppData\\Roaming\\Intel\\igfxsvc.dll,Start  (unsigned dll)' },
      { id: 'i08', t: '13:04:12', src: 'process', host: 'WS-LAB-02', user: 'lina', type: 'Process create', msg: 'explorer.exe > chrome.exe (signed)' },
      { id: 'i09', t: '12:00:00', src: 'ops', host: 'IDS-EDGE', user: '', type: 'Placement', msg: 'IDS-EDGE is a span port, detection only. It cannot block. Blocking is a separate firewall change. Fail-open is by design on this tap.' },
      { id: 'i10', t: '13:10:00', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.12.22:52210 -> 198.51.100.23:443  (matches the established conns, not the s0 attempt)' },
      { id: 'i11', t: '13:12:40', src: 'ids', host: 'IDS-EDGE', user: '', type: 'eve alert', msg: 'signature_id=2026002  signature="ET INFO generic HTTP"  src_ip=10.10.12.22  dest_ip=192.0.2.44  action=allowed  (lina browsing a news page, daily)' },
      { id: 'i12', t: '13:15:00', src: 'sandbox', host: 'SBX-01', user: 'soc', type: 'Detonation', msg: 'igfxsvc.dll from WS-LAB-02: HTTPS POST /gate.php to 198.51.100.23 every 60s. Verdict MALICIOUS. Same hash family as the earlier loader case.' },
    ],
    key: [
      { id: 'k-alert', label: 'The signature names /gate.php and the action is allowed', rows: ['i03', 'i09'], why: 'Read alert.action. Allowed on a span means the packet was observed, not stopped. The signature text names the beacon URI, which is more than a port match.' },
      { id: 'k-zeek', label: 'Established connections of the same size, once a minute', rows: ['i02', 'i04', 'i05'], why: 'conn_state sf means the handshake completed. Identical small byte counts once a minute fit a beacon. The s0 row to a different IP never connected and is not this alert.' },
      { id: 'k-proc', label: 'An unsigned DLL was started just before the beacons', rows: ['i07', 'i12'], why: 'rundll32 of an unsigned DLL in AppData, and a sandbox that posts to the same URI, ties the signature to a process. Chrome on the same host is not the parent.' },
    ],
    related: ['i01', 'i10'],
    verdict: 'tp',
    parQueries: 4,
    writeup: [
      { label: 'Says the IDS did not block', any: ['allowed', 'span', 'did not block', 'tap', 'detection only'] },
      { label: 'Describes the established beacon', any: ['sf', 'beacon', '60', 'gate.php', 'established'] },
      { label: 'Names the DLL or rundll32', any: ['rundll32', 'igfxsvc', 'dll', 'unsigned'] },
    ],
    explanation:
      'True positive. Suricata saw POST /gate.php from WS-LAB-02 to 198.51.100.23 and, because this sensor is a span, the action was allowed. Zeek shows those connections completed (sf) with the same small sizes once a minute. An s0 to a different IP is a failed handshake, not a second beacon. rundll32 had just started an unsigned DLL that the sandbox already calls malicious. Isolate the host and block 198.51.100.23 on the firewall. The IDS cannot do that itself.',
    strong: [
      'alert.action=allowed is not a benign verdict. On a tap it means nobody was in a position to drop the packet.',
      'Use Zeek to test the signature: sf and repeated sizes support it, s0 means the flow never existed.',
      'Do not isolate on the generic HTTP info signature. That one is the news page.',
      'The block belongs on the firewall. Writing a ticket that says "IDS blocked it" is the misconception this case is for.',
    ],
  },

  // ------------------------------------------------------------------ L2-12: intel lookup
  {
    id: 'siem-l2-intel-loader',
    tier: 'l2',
    title: 'Look it up before you block the CDN',
    difficulty: 3,
    date: 'Fri 2 Oct 2026',
    summary: 'A workstation called a new name that looks like a CDN. Enrich the IP, the domain and the file hash in the indicator panel before you decide. Unknown is not the same as clean.',
    requires: { skills: ['l2-intel'] },
    alert: {
      id: 'ALRT-6712',
      name: 'New domain contacted by a workstation',
      severity: 'medium',
      time: '15:14:20',
      host: 'WS-FIN-02',
      user: 'omar',
      source: 'DNS analytics',
      detail: 'WS-FIN-02 resolved update-cdn-sync.example, a name with no prior hits in this network, and downloaded a file.',
    },
    logs: [
      { id: 'n01', t: '15:12:01', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'WS-FIN-02 (10.10.6.40) query A update-cdn-sync.example -> 198.51.100.77' },
      { id: 'n02', t: '15:12:40', src: 'proxy', host: 'PROXY', user: 'omar', type: 'GET 200', msg: 'omar WS-FIN-02 GET https://update-cdn-sync.example/edge/refresh.bin 200 application/octet-stream  sha256=a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90' },
      { id: 'n03', t: '15:13:10', src: 'process', host: 'WS-FIN-02', user: 'omar', type: 'Process create', msg: 'chrome.exe > rundll32.exe C:\\Users\\omar\\Downloads\\refresh.bin,Start' },
      { id: 'n04', t: '15:14:20', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.6.40:53110 -> 198.51.100.77:443 bytes_out=412 bytes_in=96' },
      { id: 'n05', t: '15:15:21', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.6.40:53144 -> 198.51.100.77:443 bytes_out=412 bytes_in=96' },
      { id: 'n06', t: '15:16:22', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.6.40:53180 -> 198.51.100.77:443 bytes_out=412 bytes_in=96' },
      { id: 'n07', t: '15:11:00', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'WS-FIN-02 query A cdn.corp.example -> 192.0.2.20 (the company CDN, seen daily)' },
      { id: 'n08', t: '15:11:05', src: 'proxy', host: 'PROXY', user: 'omar', type: 'GET 200', msg: 'omar GET https://cdn.corp.example/static/app.js 200  (no hash in the indicator panel for this name)' },
      { id: 'n09', t: '15:20:00', src: 'ops', host: 'INTEL-NOTE', user: '', type: 'Feed age', msg: 'The mock indicator panel is the feed for this exercise. A name or hash with no record is unknown, not clean. Do not block 192.0.2.20 because a different name was bad.' },
      { id: 'n10', t: '15:22:18', src: 'process', host: 'WS-FIN-02', user: 'omar', type: 'Registry', msg: 'rundll32.exe set HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\EdgeRefresh to the downloaded file' },
      { id: 'n11', t: '15:30:00', src: 'email', host: 'MAIL-GW', user: 'omar', type: 'Delivered', msg: 'To omar@corp.example From: "IT" <it@corp.example> Subject: "Laptop refresh"  spf=pass dkim=pass dmarc=pass header.d=corp.example  no links' },
      { id: 'n12', t: '15:05:00', src: 'proxy', host: 'PROXY', user: 'omar', type: 'GET 200', msg: 'omar GET https://news.example.org/ 200 (ordinary browsing before the download)' },
    ],
    key: [
      { id: 'k-ind', label: 'The domain, the IP and the hash are one indicator set', rows: ['n01', 'n02'], why: 'update-cdn-sync.example resolves to 198.51.100.77 and the download is hash a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90. Look all three up. The panel has a malicious reputation, a three-day-old registration, passive DNS between the name and the IP, and a sandbox note for that hash. A hash hit is this file, not the next build.' },
      { id: 'k-run', label: 'The browser launched the download and it added a Run key', rows: ['n03', 'n10'], why: 'chrome.exe starting rundll32 on a download, then a Run key named EdgeRefresh, is execution and persistence. The sandbox note on the hash describes that same key.' },
      { id: 'k-beacon', label: 'Small repeated connections to the enriched IP', rows: ['n04', 'n05', 'n06'], why: 'Once a minute, same byte counts, to the IP the domain just resolved to. That matches the sandbox\'s 60-second POST, not a CDN page load.' },
      { id: 'k-notcdn', label: 'The real company CDN is a different name and was not looked up as malicious', rows: ['n07', 'n09'], why: 'cdn.corp.example is the daily asset host. Blocking "CDN-looking names" or the company range because a lookalike was bad is how a feed becomes an outage. Unknown on a name you did not query is not a verdict either.' },
    ],
    related: ['n08', 'n12'],
    verdict: 'tp',
    parQueries: 5,
    writeup: [
      { label: 'Names the domain, IP or hash that was enriched', any: ['update-cdn-sync', '198.51.100.77', 'a1b2c3d4', 'hash', 'lookup', 'reputation'] },
      { label: 'Says the file ran or persisted', any: ['rundll32', 'run key', 'persistence', 'edgerefresh'] },
      { label: 'Does not treat the company CDN as the same indicator', any: ['cdn.corp', 'company cdn', 'not the cdn', 'different'] },
    ],
    explanation:
      'True positive, and the lookup is what makes it one rather than "a new domain, maybe a CDN". update-cdn-sync.example is newly registered, resolves to 198.51.100.77, and the downloaded hash is a known loader that beacons there and sets EdgeRefresh. The workstation ran it. cdn.corp.example is the company CDN and is not this indicator. Enrich, then block the name and the IP, and isolate WS-FIN-02. Do not block the company CDN because the lookalike was malicious, and do not call an unqueried name clean.',
    strong: [
      'Use the indicator panel on the IP, the domain and the hash. WHOIS age, reputation, passive DNS and the sandbox answer different questions.',
      'A hash match is strong for this file and useless against a rebuild. Keep the behaviour (the Run key, the beacon size) as well as the IOC.',
      'Unknown is not clean. The company CDN simply is not the indicator you were asked about.',
      'Contain the host and the malicious name. Scope other resolvers of update-cdn-sync.example before you call it one workstation.',
    ],
  },
];
