// Level 2 SIEM investigation cases. Same schema as content/siem-cases.js (and the ambiguous
// fields documented there), plus `tier: 'l2'`. They unlock from Level 2 skills.
// All data is fictional: RFC 5737 / private IPs and reserved example domains.

export const L2_SIEM_CASES = [
  // ------------------------------------------------------------------ L2-1: phishing with headers
  {
    id: 'siem-l2-payroll-phish',
    tier: 'l2',
    title: 'The payslip that wasn\'t',
    difficulty: 2,
    date: 'Tue 22 Sep 2026',
    summary: 'A user reports a payroll email. Read the headers, then find out who clicked, who typed a password and what the attacker did next.',
    requires: { skills: ['l2-phishing'] },
    alert: {
      id: 'ALRT-5210',
      name: 'User-reported phishing: payroll login page',
      severity: 'medium',
      time: '09:31:10',
      host: 'MAIL-GW',
      user: 'emma',
      source: 'Report-phish button',
      detail: 'emma@corp.example reported "Action required: confirm your September payslip" as phishing.',
    },
    logs: [
      { id: 'p01', t: '08:55:02', src: 'email', host: 'MAIL-GW', user: 'lena', type: 'Delivered', msg: 'To lena@corp.example  From: "IT Service Desk" <servicedesk@corp.example>  Subject: "Planned maintenance Saturday"  spf=pass dkim=pass header.d=corp.example dmarc=pass' },
      { id: 'p02', t: '09:02:14', src: 'email', host: 'MAIL-GW', user: 'emma', type: 'Delivered', msg: 'To emma@corp.example  From: "HR Payroll" <payroll@corp-example-hr.example>  Return-Path: <bounce@mailer.corp-example-hr.example>  Subject: "Action required: confirm your September payslip"  Sending IP: 203.0.113.140' },
      { id: 'p03', t: '09:02:14', src: 'email', host: 'MAIL-GW', user: 'emma', type: 'Auth results', msg: 'Authentication-Results: spf=pass smtp.mailfrom=mailer.corp-example-hr.example; dkim=pass header.d=corp-example-hr.example; dmarc=pass header.from=corp-example-hr.example  (sender domain first seen today; registered 2 days ago)' },
      { id: 'p04', t: '09:02:15', src: 'email', host: 'MAIL-GW', user: '(14 recipients)', type: 'Delivered', msg: 'Same message (same sender, subject and URL) also delivered to 14 mailboxes on the hr-all and finance-all lists, including jonas@corp.example' },
      { id: 'p05', t: '09:02:15', src: 'email', host: 'MAIL-GW', user: 'emma', type: 'URL in message', msg: 'Link target: https://payroll.corp-example-hr.example/sso/login   Display text: "https://payroll.corp.example"' },
      { id: 'p06', t: '09:10:43', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'WS-HR-04 (10.10.6.14) query A payroll.corp-example-hr.example -> 203.0.113.140' },
      { id: 'p07', t: '09:10:44', src: 'proxy', host: 'WS-HR-04', user: 'emma', type: 'GET 200', msg: 'emma WS-HR-04 GET https://payroll.corp-example-hr.example/sso/login 200 text/html (page title "Corp SSO - Sign in")' },
      { id: 'p08', t: '09:11:31', src: 'proxy', host: 'WS-HR-04', user: 'emma', type: 'POST 302', msg: 'emma WS-HR-04 POST https://payroll.corp-example-hr.example/sso/login 302 -> https://payroll.corp.example/ (form fields: username, password, otp)' },
      { id: 'p09', t: '09:13:02', src: 'proxy', host: 'WS-FIN-09', user: 'jonas', type: 'GET 200', msg: 'jonas WS-FIN-09 GET https://payroll.corp-example-hr.example/sso/login 200 text/html' },
      { id: 'p10', t: '09:14:10', src: 'proxy', host: 'WS-FIN-09', user: 'jonas', type: 'GET 200', msg: 'jonas WS-FIN-09 GET https://news.example.org/markets 200 text/html' },
      { id: 'p11', t: '09:20:00', src: 'idp', host: 'IDP', user: 'mateo', type: 'Sign-in success', msg: 'mateo@corp.example sign-in from 10.10.7.22 (corp office), device WS-SLS-02 (managed, compliant), MFA push approved' },
      { id: 'p12', t: '09:24:18', src: 'idp', host: 'IDP', user: 'emma', type: 'Sign-in success', msg: 'emma@corp.example sign-in to Webmail from 198.51.100.61 (hosting provider, new IP), device: unregistered, MFA: satisfied by one-time code entered 13 minutes earlier (session relayed)' },
      { id: 'p13', t: '09:26:40', src: 'idp', host: 'IDP', user: 'emma', type: 'New-InboxRule', msg: 'New-InboxRule by emma@corp.example from 198.51.100.61: name ".." if subject or body contains "payroll","bank","payslip" then move to "Conversation History" and mark as read' },
      { id: 'p14', t: '09:27:05', src: 'idp', host: 'IDP', user: 'emma', type: 'MailItemsAccessed', msg: 'MailItemsAccessed: 212 items read in Webmail by emma@corp.example from 198.51.100.61' },
      { id: 'p15', t: '09:29:30', src: 'idp', host: 'IDP', user: 'emma', type: 'Sign-in success', msg: 'emma@corp.example sign-in from 10.10.6.14 (corp office), device WS-HR-04 (managed), MFA push approved' },
      { id: 'p16', t: '09:31:10', src: 'email', host: 'MAIL-GW', user: 'emma', type: 'User report', msg: 'emma@corp.example reported "Action required: confirm your September payslip" as phishing' },
    ],
    key: [
      { id: 'k-domain', label: 'Lookalike sender that passes authentication for itself', rows: ['p02', 'p03'], why: 'SPF, DKIM and DMARC all pass, but only for corp-example-hr.example, a 2-day-old lookalike of corp.example. Authentication proves who sent it, not that they are trustworthy.' },
      { id: 'k-link', label: 'Link text shows the real portal, target is the lookalike', rows: ['p05'], why: 'The display text says payroll.corp.example; the real link goes to payroll.corp-example-hr.example.' },
      { id: 'k-post', label: 'emma submitted username, password and one-time code', rows: ['p08'], why: 'A POST of username, password and OTP to the lookalike, then a redirect to the real portal so nothing looks wrong: a credential-harvesting (adversary-in-the-middle) kit.' },
      { id: 'k-signin', label: 'Sign-in from a hosting IP using the relayed code', rows: ['p12'], why: 'Thirteen minutes after the POST, "emma" signs in from a hosting-provider IP on an unregistered device, with MFA satisfied by the code she typed into the fake page.' },
      { id: 'k-rule', label: 'Inbox rule hiding payroll and bank mail', rows: ['p13'], why: 'A meaningless rule name moving payroll and bank messages to an unused folder is classic business email compromise (T1564.008): the attacker hides replies while they redirect salary or payments.' },
    ],
    related: ['p04', 'p06', 'p07', 'p09', 'p14', 'p16'],
    verdict: 'tp',
    parQueries: 5,
    writeup: [
      { label: 'Names the lookalike domain', any: ['corp-example-hr', 'lookalike', 'look-alike'] },
      { label: 'Says credentials were submitted', any: ['post', 'credential', 'password', 'entered', 'submitted'] },
      { label: 'Describes the attacker sign-in', any: ['198.51.100.61', 'sign-in', 'signin', 'signed in', 'session'] },
      { label: 'Mentions the inbox rule', any: ['inbox rule', 'new-inboxrule', 'rule'] },
      { label: 'Scopes the other recipients', any: ['14', 'recipients', 'jonas', 'other users', 'mailboxes'] },
    ],
    explanation:
      'True positive: credential phishing leading to account compromise. A 2-day-old lookalike domain with its own valid SPF/DKIM/DMARC sent a fake payslip notice to 15 people. emma entered her username, password and one-time code; the kit relayed them and the attacker signed in from 198.51.100.61, read 212 emails and created an inbox rule to hide payroll and bank messages. jonas opened the page but no form submission is recorded.',
    strong: [
      'Read the headers first: everything passes, but for corp-example-hr.example. Alignment with a lookalike domain proves nothing about legitimacy.',
      'Scope in three layers: received (14 more mailboxes), clicked (proxy: emma and jonas), compromised (POST from emma, then a sign-in from a hosting IP).',
      'A one-time code does not stop a real-time relay kit: the attacker used emma\'s code within its session. Revoke sessions, not just the password.',
      'Contain: revoke emma\'s sessions, reset her password, remove the inbox rule, check sent mail and payroll changes; purge the message from all 15 mailboxes; block the domain and 203.0.113.140 / 198.51.100.61; confirm with jonas by phone that he did not type anything.',
      'Longer term: phishing-resistant MFA (FIDO2/passkeys) defeats this kind of relay.',
    ],
  },

  // ------------------------------------------------------------------ L2-2: loader via ISO + LNK
  {
    id: 'siem-l2-iso-loader',
    tier: 'l2',
    title: 'A parcel you weren\'t expecting',
    difficulty: 2,
    date: 'Wed 23 Sep 2026',
    summary: 'EDR flags a scheduled task created by rundll32. Follow it back to the delivery and forward to the C2, using the sandbox report.',
    requires: { skills: ['l2-malware'] },
    alert: {
      id: 'ALRT-5388',
      name: 'Scheduled task created by rundll32.exe',
      severity: 'high',
      time: '13:05:48',
      host: 'WS-ENG-05',
      user: 'ravi',
      source: 'EDR',
      detail: 'rundll32.exe created a scheduled task that runs a DLL from the user profile every 30 minutes.',
    },
    logs: [
      { id: 'm01', t: '12:58:01', src: 'process', host: 'WS-ENG-05', user: 'SYSTEM', type: 'Process create', msg: 'svchost.exe > GoogleUpdate.exe /ua /installsource scheduler (signed: Google LLC, valid)' },
      { id: 'm02', t: '13:01:10', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'WS-ENG-05 (10.10.8.35) query A teams.messaging.example -> 192.0.2.44' },
      { id: 'm03', t: '13:02:10', src: 'email', host: 'MAIL-GW', user: 'ravi', type: 'Delivered', msg: 'To ravi@corp.example  From: "Parcel Service" <notice@parcel-track-delivery.example>  Subject: "Delivery failed: reschedule your parcel"  Attachment: Parcel_88213.zip (contains Parcel_88213.iso)  spf=pass dkim=none dmarc=none' },
      { id: 'm04', t: '13:05:30', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'Image mount', msg: 'explorer.exe mounted Parcel_88213.iso (from Downloads\\Parcel_88213.zip) as drive E:. Contents: Parcel_88213.lnk, data\\pd.dll (hidden)' },
      { id: 'm05', t: '13:05:44', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'Process create', msg: 'explorer.exe > cmd.exe /c start rundll32 E:\\data\\pd.dll,DllRegisterServer   (launched by E:\\Parcel_88213.lnk)' },
      { id: 'm06', t: '13:05:45', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'Process create', msg: 'cmd.exe > rundll32.exe E:\\data\\pd.dll,DllRegisterServer   (pd.dll unsigned)' },
      { id: 'm07', t: '13:05:47', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'File create', msg: 'rundll32.exe wrote C:\\Users\\ravi\\AppData\\Roaming\\Intel\\igfxsvc.dll SHA256=5b7e2c9d0a4f6e8b1c3d5f7a9b0c2e4d6f8a1b3c5d7e9f0a2b4c6d8e0f1a3b5c' },
      { id: 'm08', t: '13:05:48', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'Process create', msg: 'rundll32.exe > schtasks.exe /create /sc minute /mo 30 /tn "Intel Graphics Refresh" /tr "rundll32 C:\\Users\\ravi\\AppData\\Roaming\\Intel\\igfxsvc.dll,Start"' },
      { id: 'm09', t: '13:06:02', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'WS-ENG-05 (10.10.8.35) query A cdn.stats-telemetry.example -> 198.51.100.23' },
      { id: 'm10', t: '13:06:03', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.8.35:52210 -> 198.51.100.23:443 bytes_out=412 bytes_in=96' },
      { id: 'm11', t: '13:07:04', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.8.35:52231 -> 198.51.100.23:443 bytes_out=412 bytes_in=96' },
      { id: 'm12', t: '13:08:03', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.8.35:52247 -> 198.51.100.23:443 bytes_out=412 bytes_in=96' },
      { id: 'm13', t: '13:10:00', src: 'process', host: 'WS-ENG-05', user: 'ravi', type: 'Process create', msg: 'explorer.exe > chrome.exe (signed: Google LLC, valid)' },
      { id: 'm14', t: '13:12:30', src: 'firewall', host: 'FW-EDGE', user: '', type: 'DENY', msg: 'DENY TCP 203.0.113.9:40001 -> 10.10.8.35:3389 rule=default-deny' },
      { id: 'm15', t: '13:20:15', src: 'sandbox', host: 'SBX-01', user: 'soc', type: 'Detonation', msg: 'igfxsvc.dll (SHA256 5b7e2c9d...a3b5c): injects into explorer.exe (VirtualAllocEx, WriteProcessMemory, CreateRemoteThread); HTTPS POST /gate.php to 198.51.100.23 every ~60 s; verdict MALICIOUS (commodity loader)' },
      { id: 'm16', t: '13:21:00', src: 'sandbox', host: 'SBX-01', user: 'soc', type: 'Static', msg: 'pd.dll: PE32 DLL, .text entropy 7.86 (packed), exports DllRegisterServer and Start, compile timestamp 2009-03-14 (implausible, likely forged)' },
      { id: 'm17', t: '13:22:40', src: 'email', host: 'MAIL-GW', user: '(6 recipients)', type: 'Message trace', msg: 'Same sender and attachment hash delivered to 6 more mailboxes today (engineering and sales)' },
    ],
    key: [
      { id: 'k-delivery', label: 'ISO inside a ZIP from a lookalike courier', rows: ['m03', 'm04'], why: 'Containers such as ISO hide the payload from mail scanners and, on older builds, from mark-of-the-web warnings. A parcel notice from an unknown domain with no DKIM or DMARC is the lure.' },
      { id: 'k-exec', label: 'The LNK launched rundll32 with an unsigned DLL from the ISO', rows: ['m05', 'm06'], why: 'A shortcut that runs `rundll32 E:\\data\\pd.dll` is the user-execution step (T1204.002) using a signed Windows binary to load the malware (T1218.011).' },
      { id: 'k-persist', label: 'DLL copied to AppData and a 30-minute scheduled task', rows: ['m07', 'm08'], why: 'The loader copies itself under a fake Intel name and creates "Intel Graphics Refresh" to run it every 30 minutes: persistence via T1053.005 plus masquerading.' },
      { id: 'k-c2', label: 'Regular beacons to 198.51.100.23', rows: ['m09', 'm10', 'm11', 'm12'], why: 'A new domain, then identical small connections every ~60 seconds: command-and-control check-ins.' },
      { id: 'k-sbx', label: 'Sandbox: injection, /gate.php C2, packed DLL', rows: ['m15', 'm16'], why: 'Dynamic analysis confirms process injection and the C2 endpoint; static analysis shows packing and a forged timestamp. Together: malicious loader.' },
    ],
    related: ['m17'],
    verdict: 'tp',
    parQueries: 5,
    writeup: [
      { label: 'Describes the ISO/ZIP delivery', any: ['iso', 'zip', 'attachment', 'parcel'] },
      { label: 'Names the rundll32 / DLL execution', any: ['rundll32', 'pd.dll', 'igfxsvc', 'dll'] },
      { label: 'Mentions the scheduled task persistence', any: ['scheduled task', 'schtasks', 'intel graphics refresh', 'persistence'] },
      { label: 'Identifies the C2', any: ['198.51.100.23', 'gate.php', 'beacon', 'c2', 'stats-telemetry'] },
    ],
    explanation:
      'True positive: a commodity loader. A fake parcel notice delivered a ZIP containing an ISO. ravi mounted it and opened the shortcut, which ran rundll32 on a hidden, packed, unsigned DLL. The DLL copied itself into AppData as igfxsvc.dll, created a 30-minute scheduled task named "Intel Graphics Refresh", and began beaconing to cdn.stats-telemetry.example (198.51.100.23). The sandbox confirms injection into explorer.exe and HTTPS C2 to /gate.php. Six other people received the same attachment.',
    strong: [
      'Start from the alert (schtasks created by rundll32) and walk backwards in the process tree to the delivery, then forwards to the network.',
      'Use static and dynamic results together: packing and a forged timestamp (static) plus injection and C2 (dynamic).',
      'Ignore the noise: GoogleUpdate and chrome are signed and normal; the RDP DENY is unrelated internet scanning.',
      'Loaders sell access to other criminals, so a loader today can mean ransomware tomorrow: isolate WS-ENG-05, block the domain and IP, delete the task and DLL, and purge the email from the 6 other mailboxes (and check whether any of them mounted the ISO).',
      'Hunt with durable indicators: rundll32 loading DLLs from AppData or mounted drives, tasks named like hardware vendors, and the /gate.php URI.',
    ],
  },

  // ------------------------------------------------------------------ L2-3: ransomware rule, benign
  {
    id: 'siem-l2-mass-rename',
    tier: 'l2',
    title: 'Ransomware at 01:00?',
    difficulty: 2,
    date: 'Sat 26 Sep 2026',
    summary: 'The ransomware rule fires on the finance file server in the middle of the night: thousands of files renamed to a new extension.',
    requires: { skills: ['l2-alert-triage'] },
    alert: {
      id: 'ALRT-5503',
      name: 'Possible ransomware: mass file rename by a single process',
      severity: 'critical',
      time: '01:04:31',
      host: 'SRV-FS02',
      user: 'svc_vaultsync',
      source: 'EDR',
      detail: 'More than 3,000 files renamed to a new extension (.vsarc) by one process within 5 minutes on SRV-FS02.',
    },
    logs: [
      { id: 'r01', t: '00:30:12', src: 'winevt', host: 'SRV-FS02', user: 'svc_backup', type: 'Security 4624', msg: 'An account was successfully logged on. Account: svc_backup  Logon Type: 3  Source: 10.10.20.30 (SRV-BKP01)' },
      { id: 'r02', t: '00:59:00', src: 'ops', host: 'CHANGE-CAL', user: '', type: 'Change window', msg: 'CHG-5120 (approved): archive migration on SRV-FS02. VaultSync archiver moves Finance files older than 3 years to ARCH-COLD01 and leaves .vsarc stub files. Window Sat 01:00-04:00. Owner: storage team. Account: svc_vaultsync' },
      { id: 'r03', t: '01:00:05', src: 'winevt', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'Security 4624', msg: 'An account was successfully logged on. Account: svc_vaultsync  Logon Type: 5 (service)' },
      { id: 'r04', t: '01:00:07', src: 'process', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'Process create', msg: 'services.exe > C:\\Program Files\\VaultSync\\vsarchiver.exe --job archive-3y --share D:\\Shares\\Finance  (signed: VaultSync Software Ltd, valid; seen on this host monthly)' },
      { id: 'r05', t: '01:02:11', src: 'process', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'File rename', msg: 'vsarchiver.exe renamed 1,204 files under D:\\Shares\\Finance\\2021\\ to *.vsarc (original size 38 GB, stubs 4 KB each)' },
      { id: 'r06', t: '01:03:00', src: 'dns', host: 'DNS01', user: '', type: 'Query A', msg: 'SRV-FS02 (10.10.20.22) query A arch-cold01.corp.example -> 10.10.20.80' },
      { id: 'r07', t: '01:04:30', src: 'process', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'File rename', msg: 'vsarchiver.exe renamed 2,340 files under D:\\Shares\\Finance\\2022\\ to *.vsarc' },
      { id: 'r08', t: '01:05:00', src: 'firewall', host: 'FW-CORE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.20.22:50122 -> 10.10.20.80:443 rule=fs-to-archive bytes_out=4.2GB' },
      { id: 'r09', t: '01:05:10', src: 'process', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'Network conn', msg: 'vsarchiver.exe -> 10.10.20.80:443 (ARCH-COLD01), TLS, 4.2 GB sent so far' },
      { id: 'r10', t: '01:06:30', src: 'firewall', host: 'FW-EDGE', user: '', type: 'DENY', msg: 'DENY TCP 198.51.100.200:40112 -> 10.10.20.22:445 rule=default-deny' },
      { id: 'r11', t: '01:08:00', src: 'ops', host: 'EDR', user: '', type: 'EDR query', msg: 'Search SRV-FS02, last 24 h: no vssadmin, wbadmin, bcdedit or wmic shadowcopy executions; no new files named *README*, *DECRYPT*, *RESTORE*; no outbound connections to the internet from vsarchiver.exe' },
      { id: 'r12', t: '01:10:00', src: 'process', host: 'SRV-FS02', user: 'SYSTEM', type: 'Process create', msg: 'services.exe > C:\\Windows\\System32\\svchost.exe -k netsvcs (signed: Microsoft Windows)' },
      { id: 'r13', t: '01:12:00', src: 'process', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'File create', msg: 'vsarchiver.exe wrote D:\\Shares\\Finance\\_archive_manifest_2026-09-26.csv (3,544 entries)' },
      { id: 'r14', t: '01:15:00', src: 'winevt', host: 'SRV-FS02', user: 'svc_vaultsync', type: 'Security 4663', msg: 'An attempt was made to access an object. Object: D:\\Shares\\Finance\\2021\\Q3\\ledger.xlsx.vsarc  Accesses: WriteData  Process: vsarchiver.exe  Account: svc_vaultsync' },
    ],
    key: [
      { id: 'k-change', label: 'Approved change for exactly this job', rows: ['r02'], why: 'CHG-5120 names the host, the tool, the .vsarc stubs, the account and a window that contains the alert.' },
      { id: 'k-signed', label: 'Signed archiver started by services.exe as its service account', rows: ['r04'], why: 'A validly signed, known binary in Program Files, started by the Service Control Manager under svc_vaultsync and seen monthly: not a dropped tool.' },
      { id: 'k-dest', label: 'Data goes to the internal archive server', rows: ['r06', 'r08', 'r09'], why: 'The traffic goes to ARCH-COLD01 (10.10.20.80) over an existing rule, not to the internet. That matches archiving, not exfiltration.' },
      { id: 'k-noprec', label: 'No ransomware precursors', rows: ['r11'], why: 'Ransomware nearly always deletes shadow copies and backups (T1490) and drops ransom notes. None of that happened.' },
    ],
    related: ['r03', 'r05', 'r07', 'r13', 'r14'],
    verdict: 'btp',
    parQueries: 4,
    writeup: [
      { label: 'Cites the change ticket', any: ['chg-5120', 'change', 'approved'] },
      { label: 'Identifies the signed archiver', any: ['vsarchiver', 'vaultsync', 'signed'] },
      { label: 'Notes the internal destination', any: ['arch-cold01', '10.10.20.80', 'internal', 'archive server'] },
      { label: 'Notes the missing ransomware signs', any: ['vssadmin', 'shadow', 'ransom note', 'precursor', 'no ransom'] },
    ],
    explanation:
      'Benign true positive. Thousands of files really were renamed, so the rule worked. But it was the approved CHG-5120 archive job: a validly signed VaultSync binary started by services.exe under its service account, replacing old files with .vsarc stubs and sending the data to the internal archive server. There are no shadow-copy deletions, no ransom notes and no internet traffic.',
    strong: [
      'A critical rule deserves fast, careful checks, not panic: who ran it, what binary, where is the data going, and are the usual ransomware precursors present?',
      'Check for what should be there if it were ransomware (shadow deletion, ransom notes, encryption-sized writes, internet traffic) as well as what is there.',
      'Confirm the change is real: the ticket, the account, the window and the tool all match.',
      'Tune narrowly: exclude vsarchiver.exe (by signer and path) under svc_vaultsync on SRV-FS02 during approved archive windows, not the whole server.',
      'Tell the storage team the job trips the ransomware rule, so future archive windows can be announced to the SOC.',
    ],
  },

  // ------------------------------------------------------------------ L2-4: ambiguous Kerberoasting
  {
    id: 'siem-l2-rc4-tickets',
    tier: 'l2',
    title: 'Forty service tickets in two minutes',
    difficulty: 3,
    ambiguous: true,
    date: 'Thu 24 Sep 2026',
    summary: 'An IT workstation requests RC4 Kerberos tickets for dozens of service accounts. Kerberoasting, or the new inventory tool? The EDR sensor on the host is degraded.',
    requires: { skills: ['l2-siem', 'l2-attack'] },
    alert: {
      id: 'ALRT-5431',
      name: 'Possible Kerberoasting: many RC4 service tickets from one account',
      severity: 'high',
      time: '15:42:30',
      host: 'SRV-DC01',
      user: 'it-omar',
      source: '10.10.9.41 (WS-IT-09)',
      detail: '38 Kerberos service ticket requests (4769) with encryption type 0x17 (RC4) for 38 different service accounts in 2 minutes, all from WS-IT-09.',
    },
    logs: [
      { id: 'k01', t: '09:00:00', src: 'ops', host: 'CHANGE-CAL', user: '', type: 'Change window', msg: 'CHG-5099 (approved): pilot of AssetScope inventory tool, which enumerates service principal names (SPNs) to map services. Pilot host: WS-IT-11. Owner: it-omar. Runs: Thu-Fri, business hours' },
      { id: 'k02', t: '14:10:00', src: 'ops', host: 'EDR', user: '', type: 'Sensor status', msg: 'WS-IT-09 sensor DEGRADED since 14:02 (driver update pending reboot): process and network telemetry not collected. Heartbeat only.' },
      { id: 'k03', t: '15:38:12', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'Security 4624', msg: 'An account was successfully logged on. Account: it-omar  Logon Type: 3  Source: 10.10.9.41 (WS-IT-09)' },
      { id: 'k04', t: '15:40:28', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'LDAP query', msg: 'Directory service query from 10.10.9.41 (it-omar): (&(objectClass=user)(servicePrincipalName=*)) returned 41 accounts' },
      { id: 'k05', t: '15:40:31', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'Security 4769', msg: 'A Kerberos service ticket was requested. Account: it-omar  Service: svc_sql  Ticket Encryption Type: 0x17 (RC4)  Client: 10.10.9.41' },
      { id: 'k06', t: '15:40:32', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'Security 4769', msg: 'A Kerberos service ticket was requested. Account: it-omar  Service: svc_backup  Ticket Encryption Type: 0x17 (RC4)  Client: 10.10.9.41' },
      { id: 'k07', t: '15:40:33', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'Security 4769', msg: 'A Kerberos service ticket was requested. Account: it-omar  Service: svc_vaultsync  Ticket Encryption Type: 0x17 (RC4)  Client: 10.10.9.41' },
      { id: 'k08', t: '15:42:30', src: 'winevt', host: 'SRV-DC01', user: 'it-omar', type: 'Security 4769', msg: '...35 more 4769 events from 15:40:34 to 15:42:30 for other service accounts (svc_web, svc_crm, svc_print, ...), all encryption type 0x17, client 10.10.9.41' },
      { id: 'k09', t: '15:30:05', src: 'winevt', host: 'SRV-DC01', user: 'svc_sql', type: 'Security 4769', msg: 'A Kerberos service ticket was requested. Account: SRV-APP01$  Service: svc_sql  Ticket Encryption Type: 0x12 (AES256)  Client: 10.10.30.11' },
      { id: 'k10', t: '15:41:00', src: 'ops', host: 'DIRECTORY', user: '', type: 'Account info', msg: 'it-omar: IT systems administrator, on the AssetScope pilot team. Workstations assigned: WS-IT-09 (daily laptop), WS-IT-11 (pilot VM)' },
      { id: 'k11', t: '15:44:10', src: 'firewall', host: 'FW-CORE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.10.9.41:51020 -> 10.10.1.11:88 rule=clients-to-dc (Kerberos)' },
      { id: 'k12', t: '15:45:00', src: 'ops', host: 'DIRECTORY', user: '', type: 'Account info', msg: 'Service account password ages: svc_sql 6 years, svc_backup 4 years, svc_vaultsync 3 months. 22 of the 38 accounts still allow RC4.' },
      { id: 'k13', t: '15:50:00', src: 'winevt', host: 'SRV-DC01', user: '', type: 'Search', msg: 'No logons (4624/4768) by any of the 38 service accounts from unusual hosts since 15:40' },
      { id: 'k14', t: '15:52:18', src: 'proxy', host: 'WS-IT-09', user: 'it-omar', type: 'GET 200', msg: 'it-omar WS-IT-09 GET https://docs.assetscope-vendor.example/guides/spn-discovery 200 text/html' },
    ],
    key: [
      { id: 'k-burst', label: '38 RC4 service tickets for 38 accounts in 2 minutes', rows: ['k05', 'k06', 'k07', 'k08'], why: 'Kerberoasting (T1558.003) requests service tickets for many SPN accounts, preferably RC4, and cracks them offline. It is also exactly what an SPN-mapping tool does.' },
      { id: 'k-ldap', label: 'SPN enumeration right before', rows: ['k04'], why: 'An LDAP query for every account with an SPN is the usual first step of both Kerberoasting tools and inventory tools.' },
      { id: 'k-edrgap', label: 'No process telemetry from WS-IT-09', rows: ['k02'], why: 'The one fact that would settle it (which program made the requests) is missing: the sensor is degraded.' },
      { id: 'k-change', label: 'The approved pilot runs on WS-IT-11, not WS-IT-09', rows: ['k01'], why: 'The change covers the tool and the owner, but a different host. A pilot that moved to his laptop is plausible; so is an attacker on his laptop using his account.' },
    ],
    related: ['k03', 'k10', 'k12', 'k13', 'k14'],
    verdict: 'tp',
    defensible: { tp: 1, btp: 0.75 },
    confidence: { low: 0.5, medium: 1, high: 0 },
    parQueries: 4,
    gaps: [
      { id: 'gk-proc', correct: true, text: 'Which program on WS-IT-09 made the requests: the EDR sensor is degraded.', why: 'AssetScope.exe versus Rubeus or a PowerShell script would decide it almost on its own.' },
      { id: 'gk-omar', correct: true, text: 'Whether it-omar was actually running the pilot from his laptop.', why: 'A phone call to omar (not an email or chat) settles whether this was him and whether the pilot moved.' },
      { id: 'gk-crack', correct: true, text: 'Whether the tickets can be cracked: several accounts have old passwords and still allow RC4.', why: 'If this is Kerberoasting, the risk is set by password strength. svc_sql\'s 6-year-old password is the real exposure.' },
      { id: 'gk-4769', correct: false, text: 'Whether the 4769 events really mean service tickets were issued.', why: 'They do: 4769 is logged on the DC when a service ticket is requested and issued. That part is not in doubt.' },
      { id: 'gk-fw', correct: false, text: 'Whether the firewall allowed Kerberos traffic to the DC.', why: 'It did (k11), and it always does for clients. That does not help decide between tool and attacker.' },
      { id: 'gk-none', correct: false, text: 'Nothing: the change ticket covers it.', why: 'The ticket names a different host, and nothing shows which program ran. It supports one story, it does not prove it.' },
    ],
    steps: {
      'verify-user': { rating: 'best', why: 'Call omar on a known number: did he run AssetScope from WS-IT-09 at 15:40? If he did not, it is almost certainly an attack using his account.' },
      'more-logs': { rating: 'best', why: 'Get the missing process data: reboot the sensor, or pull the local Sysmon/4688 events from WS-IT-09.' },
      escalate: { rating: 'best', why: 'Hand it to Tier 2 as possible Kerberoasting, medium confidence, with the EDR gap and the host mismatch stated. Credential theft is time-critical because cracking happens offline.' },
      contain: { rating: 'ok', why: 'Isolating an admin laptop is disruptive but defensible if omar cannot be reached; rotating the weakest service account passwords (svc_sql) is a sensible precaution either way.' },
      'check-edr': { rating: 'ok', why: 'Worth a look, but the sensor is degraded: it will not show the process until it is fixed.' },
      close: { rating: 'bad', why: 'The change ticket names another host and no process is known. Closing leaves a possible credential-theft attack unexamined.' },
      wait: { rating: 'bad', why: 'Kerberoasted tickets are cracked offline, out of sight. By the time the attacker logs in with svc_sql it is too late to prevent.' },
      reimage: { rating: 'bad', why: 'Wiping the laptop destroys the one place the answer lives, and does nothing about tickets that may already be cracked.' },
    },
    writeup: [
      { label: 'Says what cannot be confirmed', any: ['cannot', "can't", 'unable', 'unclear', 'unknown', 'unverified', 'not sure', 'uncertain', 'degraded'] },
      { label: 'Names Kerberoasting', any: ['kerberoast', 't1558', 'service ticket', 'rc4'] },
      { label: 'Notes the host mismatch or the pilot', any: ['ws-it-11', 'assetscope', 'pilot', 'chg-5099'] },
      { label: 'Proposes verifying with omar', any: ['verify', 'confirm', 'call', 'phone', 'ask', 'contact'] },
    ],
    explanation:
      'Genuinely ambiguous. The pattern (SPN enumeration, then RC4 service tickets for 38 accounts) is textbook Kerberoasting, and it is also what AssetScope does. The approved pilot and the vendor docs point to omar testing the tool; the wrong host and the blind EDR sensor keep an attacker on his laptop on the table. The stronger call is a suspected true positive at medium confidence: verify with omar by phone, restore the process telemetry and rotate the weakest service account passwords. Calling it an expected benign true positive is defensible if you insist on verification.',
    strong: [
      'Know what the attack looks like in logs: an LDAP query for SPN accounts, then a burst of 4769 events with encryption type 0x17 from one client.',
      'Separate facts from the story: the ticket requests are facts; "it is the pilot" is an inference the change ticket does not fully support (wrong host).',
      'Find the missing piece: the program that made the requests. Fix the sensor or pull local logs.',
      'Think about impact while you verify: a 6-year-old svc_sql password that still allows RC4 is crackable. Rotating it is cheap.',
      'Long-term fixes either way: strong (25+ character) or managed service account passwords, AES-only Kerberos, and a detection that excludes the approved pilot host only.',
    ],
    arguments: {
      tp: 'SPN enumeration followed by RC4 tickets for every service account is exactly Kerberoasting, from a host the change ticket does not cover, with no process visibility. Treat it as credential theft until proven otherwise.',
      btp: 'The account owner runs an approved pilot of a tool that does precisely this, during its scheduled days, and was reading the vendor\'s SPN discovery guide minutes later. No service account has been used anywhere unusual.',
    },
    settle: [
      'omar confirming by phone that he ran AssetScope from WS-IT-09 (and why not WS-IT-11).',
      'Process telemetry from WS-IT-09 showing which executable requested the tickets.',
      'Any logon by one of the 38 service accounts from an unusual host in the next hours or days.',
    ],
    outcome: {
      title: 'It was the pilot, on the wrong machine',
      verdict: 'btp',
      text: 'omar answered his phone at 16:05: the pilot VM WS-IT-11 had run out of disk, so he ran AssetScope from his laptop. Local logs recovered after the sensor reboot showed AssetScope.exe making the requests. The change was updated, and svc_sql and svc_backup got new long random passwords anyway, because the exercise showed how exposed they were. A careful "suspected true positive, verify" still scored well: at 15:42 nothing in the SIEM could tell the tool from an attacker.',
    },
  },
];
