// Level 3 SIEM investigation cases. Same schema as content/siem-cases.js (and the ambiguous
// fields documented there), plus `tier: 'l3'`. They unlock from Level 3 skills.
// All data is fictional: RFC 5737 / private IPs, reserved example domains, and AWS's
// documentation placeholders (account 111122223333, key AKIAIOSFODNN7EXAMPLE).

export const L3_SIEM_CASES = [
  // ------------------------------------------------------------------ L3-1: AS-REP roast to DCSync
  {
    id: 'siem-l3-asrep-dcsync',
    tier: 'l3',
    title: 'The scanner account that learned to replicate',
    difficulty: 3,
    date: 'Thu 24 Sep 2026',
    summary: 'A DC flags directory replication from a workstation. Work back through the Kerberos events to how the attacker got the account, and forward to what they took.',
    requires: { skills: ['l3-identity'] },
    alert: {
      id: 'ALRT-6120',
      name: 'Directory replication requested by a non-DC (possible DCSync)',
      severity: 'critical',
      time: '03:22:41',
      host: 'SRV-DC01',
      user: 'legacy_scan',
      source: '10.20.4.31 (WS-FIN-12)',
      detail: 'Event 4662 with DS-Replication-Get-Changes-All by legacy_scan from a workstation IP.',
    },
    logs: [
      { id: 'a01', t: '01:58:10', src: 'winevt', host: 'SRV-DC01', user: 'j.moreno', type: 'Security 4768', msg: 'A Kerberos authentication ticket (TGT) was requested. Account: j.moreno  Client: 10.20.4.31 (WS-FIN-12)  Ticket Encryption Type: 0x12  Pre-Authentication Type: 2' },
      { id: 'a02', t: '02:04:33', src: 'winevt', host: 'SRV-DC01', user: 'j.moreno', type: 'LDAP query', msg: 'Directory query from 10.20.4.31 (j.moreno): (&(objectCategory=user)(userAccountControl:1.2.840.113556.1.4.803:=4194304)) returned 2 accounts: legacy_scan, test_kiosk' },
      { id: 'a03', t: '02:04:40', src: 'winevt', host: 'SRV-DC01', user: 'legacy_scan', type: 'Security 4768', msg: 'A Kerberos authentication ticket (TGT) was requested. Account: legacy_scan  Client: 10.20.4.31 (WS-FIN-12)  Ticket Encryption Type: 0x17  Pre-Authentication Type: 0' },
      { id: 'a04', t: '02:04:41', src: 'winevt', host: 'SRV-DC01', user: 'test_kiosk', type: 'Security 4768', msg: 'A Kerberos authentication ticket (TGT) was requested. Account: test_kiosk  Client: 10.20.4.31 (WS-FIN-12)  Ticket Encryption Type: 0x17  Pre-Authentication Type: 0' },
      { id: 'a05', t: '02:30:00', src: 'winevt', host: 'SRV-DC01', user: 'SRV-BKP01$', type: 'Security 4769', msg: 'A Kerberos service ticket was requested. Account: SRV-BKP01$  Service: cifs/SRV-FS02  Ticket Encryption Type: 0x12  Client: 10.20.30.14' },
      { id: 'a06', t: '02:45:12', src: 'ops', host: 'DIRECTORY', user: '', type: 'Account info', msg: 'legacy_scan: created 2017 for the old vulnerability scanner. "Do not require Kerberos preauthentication" enabled. Member of: Scanner-Admins (delegated Replicating Directory Changes All in 2019 for a sync plug-in). Password last set 2017.' },
      { id: 'a07', t: '03:19:55', src: 'winevt', host: 'SRV-DC01', user: 'legacy_scan', type: 'Security 4768', msg: 'A Kerberos authentication ticket (TGT) was requested. Account: legacy_scan  Client: 10.20.4.31 (WS-FIN-12)  Ticket Encryption Type: 0x12  Pre-Authentication Type: 0' },
      { id: 'a08', t: '03:20:02', src: 'winevt', host: 'SRV-DC01', user: 'legacy_scan', type: 'Security 4624', msg: 'An account was successfully logged on. Account: legacy_scan  Logon Type: 3  Authentication: Kerberos  Source: 10.20.4.31 (WS-FIN-12)' },
      { id: 'a09', t: '03:20:02', src: 'winevt', host: 'SRV-DC01', user: 'legacy_scan', type: 'Security 4672', msg: 'Special privileges assigned to new logon. Account: legacy_scan  Privileges: SeSecurityPrivilege, SeBackupPrivilege' },
      { id: 'a10', t: '03:22:41', src: 'winevt', host: 'SRV-DC01', user: 'legacy_scan', type: 'Security 4662', msg: 'An operation was performed on an object. Account: legacy_scan  Object Type: domainDNS  Access: Control Access  Properties: DS-Replication-Get-Changes, DS-Replication-Get-Changes-All  Client: 10.20.4.31' },
      { id: 'a11', t: '03:22:44', src: 'winevt', host: 'SRV-DC01', user: 'legacy_scan', type: 'Replication', msg: 'DRSUAPI GetNCChanges from 10.20.4.31: objects krbtgt, Administrator, svc_backup, svc_sql and 1,204 more user objects with secrets' },
      { id: 'a12', t: '03:24:10', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.20.4.31:50412 -> 203.0.113.88:443 bytes_out=18.4 MB (no SNI)' },
      { id: 'a13', t: '03:25:00', src: 'winevt', host: 'SRV-DC02', user: 'SRV-DC01$', type: 'Replication', msg: 'Normal DC-to-DC replication SRV-DC01 -> SRV-DC02 (scheduled)' },
      { id: 'a14', t: '03:40:31', src: 'winevt', host: 'SRV-DC01', user: 'Administrator', type: 'Security 4769', msg: 'A Kerberos service ticket was requested. Account: Administrator  Service: cifs/SRV-FS02  Ticket Encryption Type: 0x12  Client: 10.20.4.31  (no 4768 for Administrator from any DC in the last 24 h)' },
      { id: 'a15', t: '03:40:33', src: 'winevt', host: 'SRV-FS02', user: 'Administrator', type: 'Security 4624', msg: 'An account was successfully logged on. Account: Administrator  Logon Type: 3  Authentication: Kerberos  Source: 10.20.4.31 (WS-FIN-12)' },
    ],
    key: [
      { id: 'k-enum', label: 'LDAP search for accounts without pre-authentication', rows: ['a02'], why: 'The UAC bit 4194304 (DONT_REQ_PREAUTH) finds AS-REP roastable accounts. A finance user running this query at 02:04 is attacker tooling, not work.' },
      { id: 'k-asrep', label: 'AS-REP roasting: RC4 TGT requests with pre-auth type 0', rows: ['a03', 'a04'], why: 'Pre-Authentication Type 0 means the DC handed out an AS-REP encrypted with the account key to anyone who asked (T1558.004). RC4 makes it faster to crack offline.' },
      { id: 'k-use', label: 'Cracked account used from the same workstation', rows: ['a07', 'a08'], why: 'Seventy-five minutes later legacy_scan authenticates from WS-FIN-12 and logs on to the DC: the offline crack of a 2017 password worked.' },
      { id: 'k-dcsync', label: 'DCSync: replication rights used from a workstation', rows: ['a10', 'a11'], why: 'Only DCs should replicate. legacy_scan holds the replication right by an old delegation, and pulls krbtgt and 1,200+ password hashes (T1003.006).' },
      { id: 'k-golden', label: 'Administrator ticket with no TGT ever issued', rows: ['a14', 'a15'], why: 'A service ticket for Administrator without any 4768 on any DC means a forged TGT: a golden ticket built from the krbtgt hash just stolen (T1558.001).' },
    ],
    related: ['a01', 'a06', 'a09', 'a12'],
    verdict: 'tp',
    parQueries: 6,
    writeup: [
      { label: 'Names AS-REP roasting or pre-auth type 0', any: ['as-rep', 'asrep', 'pre-auth', 'preauth', 't1558.004'] },
      { label: 'Names DCSync or replication', any: ['dcsync', 'replication', 'getncchanges', '4662'] },
      { label: 'Says krbtgt is compromised', any: ['krbtgt'] },
      { label: 'Names the golden ticket', any: ['golden', 'forged', 'no 4768'] },
      { label: 'Identifies WS-FIN-12 or j.moreno as the source', any: ['ws-fin-12', '10.20.4.31', 'j.moreno'] },
    ],
    explanation:
      'True positive: full domain compromise. From j.moreno\'s workstation the attacker searched for accounts without Kerberos pre-authentication, AS-REP roasted legacy_scan and test_kiosk, cracked legacy_scan\'s 2017 password, and used its forgotten replication right to DCSync krbtgt and every other hash. Eighteen minutes later a golden ticket for Administrator is in use on SRV-FS02. Treat the whole domain as compromised: isolate WS-FIN-12, disable legacy_scan, plan a double krbtgt reset and rotate privileged and service credentials.',
    strong: [
      'Work backwards from the alert: who is legacy_scan, why does it have replication rights, and how did the attacker get it (a 4768 with pre-auth type 0 is the answer).',
      'Tie the chain to one source: every malicious step comes from 10.20.4.31, starting with j.moreno\'s session.',
      'Recognise the golden ticket: Kerberos service tickets without any TGT request on any DC.',
      'Scope the damage honestly: with krbtgt and 1,200 hashes stolen, every account is burned. Recovery means a coordinated double krbtgt reset and credential rotation, after the attacker\'s access is contained.',
      'Fix the root causes: remove the replication delegation, enable pre-authentication on every account, retire legacy_scan, and alert on 4768 with pre-auth type 0 and on 4662 replication from non-DCs.',
    ],
  },

  // ------------------------------------------------------------------ L3-2: self-signed C2 (PKI)
  {
    id: 'siem-l3-localhost-cert',
    tier: 'l3',
    title: 'A certificate called localhost',
    difficulty: 2,
    date: 'Tue 22 Sep 2026',
    summary: 'The network sensor flags a self-signed certificate on an outbound TLS session. Self-signed certificates are everywhere on the inside: decide whether this one matters.',
    requires: { skills: ['l3-pki'] },
    alert: {
      id: 'ALRT-6044',
      name: 'Outbound TLS to internet host with self-signed certificate',
      severity: 'medium',
      time: '10:14:00',
      host: 'WS-HR-07',
      user: 'priya',
      source: 'Network sensor (Zeek)',
      detail: 'WS-HR-07 completed a TLS 1.2 handshake with 203.0.113.140:443; server certificate is self-signed (CN=localhost).',
    },
    logs: [
      { id: 'c01', t: '09:40:10', src: 'firewall', host: 'FW-CORE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.20.6.17:53110 -> 10.20.50.20:443 rule=clients-to-printers' },
      { id: 'c02', t: '09:40:10', src: 'proxy', host: 'ZEEK', user: '', type: 'TLS', msg: 'ssl 10.20.6.17 -> 10.20.50.20:443 (PRN-HR-02 web admin) TLSv12 validation="self signed certificate" subject="CN=PRN-HR-02, O=Example Printers" not_after=2031-05-01' },
      { id: 'c03', t: '09:58:02', src: 'email', host: 'MAIL-GW', user: 'priya', type: 'Delivered', msg: 'To priya@corp.example  From: "Recruiting Partner" <cv@talent-bridge-hiring.example>  Subject: "Candidate CV - Senior Analyst"  Attachment: CV_Anna_Lind.zip  spf=pass dkim=pass dmarc=pass (domain registered 3 days ago)' },
      { id: 'c04', t: '10:12:30', src: 'process', host: 'WS-HR-07', user: 'priya', type: 'Process create', msg: 'explorer.exe > wscript.exe "C:\\Users\\priya\\Downloads\\CV_Anna_Lind\\CV_Anna_Lind.pdf.js"' },
      { id: 'c05', t: '10:12:34', src: 'process', host: 'WS-HR-07', user: 'priya', type: 'Process create', msg: 'wscript.exe > rundll32.exe C:\\Users\\priya\\AppData\\Local\\Temp\\tmp4F21.dat,Start (unsigned)' },
      { id: 'c06', t: '10:13:00', src: 'proxy', host: 'ZEEK', user: '', type: 'TLS', msg: 'ssl 10.20.6.17 -> 203.0.113.140:443 TLSv12 server_name=- validation="self signed certificate" ja3=72a589da586844d7f0818ce684948eea' },
      { id: 'c07', t: '10:13:00', src: 'proxy', host: 'ZEEK', user: '', type: 'x509', msg: 'x509 subject="CN=localhost" issuer="CN=localhost" serial=00 not_valid_before=2026-09-21 not_valid_after=2036-09-18 basic_constraints=CA:TRUE san=-' },
      { id: 'c08', t: '10:14:00', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.20.6.17:53188 -> 203.0.113.140:443 bytes_out=1.2 KB bytes_in=0.4 KB duration=0.7s' },
      { id: 'c09', t: '10:15:00', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.20.6.17:53201 -> 203.0.113.140:443 bytes_out=1.2 KB bytes_in=0.4 KB duration=0.7s' },
      { id: 'c10', t: '10:16:00', src: 'firewall', host: 'FW-EDGE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.20.6.17:53230 -> 203.0.113.140:443 bytes_out=1.2 KB bytes_in=0.4 KB duration=0.7s' },
      { id: 'c11', t: '10:16:30', src: 'proxy', host: 'WS-HR-07', user: 'priya', type: 'GET 200', msg: 'priya WS-HR-07 GET https://intranet.corp.example/hr/policies 200 text/html (valid certificate, internal CA)' },
      { id: 'c12', t: '10:18:00', src: 'proxy', host: 'ZEEK', user: '', type: 'JA3 search', msg: 'ja3=72a589da586844d7f0818ce684948eea seen from 1 internal host (10.20.6.17) in 30 days; never to any destination with an SNI' },
      { id: 'c13', t: '10:19:00', src: 'dns', host: 'DNS01', user: '', type: 'Search', msg: 'No DNS query from any host resolved to 203.0.113.140 in 30 days (connections go straight to the IP)' },
    ],
    key: [
      { id: 'k-exec', label: 'A .pdf.js "CV" ran and launched an unsigned DLL', rows: ['c04', 'c05'], why: 'A double extension run by wscript, then rundll32 loading an unsigned file from Temp: the user opened a script disguised as a CV (T1204.002, T1218.011).' },
      { id: 'k-cert', label: 'Fresh self-signed "localhost" certificate, ten years, CA:TRUE', rows: ['c06', 'c07'], why: 'Issuer = subject, CN=localhost, serial 00, no SAN and a ten-year validity: a framework default no public CA would issue (public certificates are capped at 200 days). Minted the day before.' },
      { id: 'k-beacon', label: 'Identical sessions every 60 seconds to a raw IP', rows: ['c08', 'c09', 'c10'], why: 'Same size, same duration, fixed interval, no SNI and no DNS lookup: machine check-ins to a C2 server, not browsing.' },
      { id: 'k-ja3', label: 'A client fingerprint only this host has', rows: ['c12'], why: 'The JA3 hash is unique to WS-HR-07 and never used with an SNI: not a browser, but the implant\'s own TLS client. Pivoting on it scopes other victims (none so far).' },
    ],
    related: ['c03', 'c13'],
    verdict: 'tp',
    parQueries: 5,
    writeup: [
      { label: 'Explains why this certificate is suspicious', any: ['localhost', 'self-signed', 'self signed', 'ten years', '10 years'] },
      { label: 'Describes the beaconing', any: ['beacon', '60 s', 'every 60', 'interval', 'c2'] },
      { label: 'Links it to the process chain', any: ['wscript', 'rundll32', '.pdf.js', 'cv'] },
      { label: 'Uses the JA3 or IP to scope', any: ['ja3', '203.0.113.140', 'pivot', 'other hosts'] },
    ],
    explanation:
      'True positive: C2 over TLS. priya opened a "CV" that was really a JavaScript file; it started an unsigned DLL through rundll32, which beacons every 60 seconds to 203.0.113.140 using a default self-signed certificate (CN=localhost, ten-year validity, created the day before). The printer\'s self-signed certificate earlier is the normal internal kind and is noise. Isolate WS-HR-07, block the IP and JA3, purge the email and check the other recipients.',
    strong: [
      'Self-signed is a lead, not a verdict: the printer (c02) is self-signed too and perfectly normal.',
      'Read the certificate like an analyst: CN=localhost, serial 00, no SAN, CA:TRUE, ten years, created yesterday. Nothing public looks like that.',
      'Confirm with behaviour: no SNI, no DNS, fixed 60-second interval, identical sizes, and a process chain that explains it.',
      'Scope with the fingerprint: the JA3 is unique to this host, so there is no second victim yet.',
    ],
  },

  // ------------------------------------------------------------------ L3-3: detection rule FP
  {
    id: 'siem-l3-shadow-rule',
    tier: 'l3',
    title: 'The rule that cried ransomware',
    difficulty: 1,
    date: 'Wed 23 Sep 2026',
    summary: 'A new detection for shadow copy deletion fires on a file server at night. Check what really ran, and whether the rule does what its title says.',
    requires: { skills: ['l3-detection'] },
    alert: {
      id: 'ALRT-6071',
      name: 'Shadow copy deletion (possible ransomware precursor, T1490)',
      severity: 'high',
      time: '01:00:04',
      host: 'SRV-FS02',
      user: 'svc_backup',
      source: 'Sigma rule "vss_shadow_manipulation" v1 (deployed yesterday)',
      detail: 'Process command line matched: Image endswith \\vssadmin.exe AND CommandLine contains "shadows".',
    },
    logs: [
      { id: 'r01', t: '00:55:00', src: 'ops', host: 'CHANGE-CAL', user: '', type: 'Schedule', msg: 'Nightly job "VSS health check" on SRV-FS02 at 01:00 (owner: backup team, since 2023)' },
      { id: 'r02', t: '00:59:58', src: 'process', host: 'SRV-FS02', user: 'svc_backup', type: 'Process create', msg: 'taskeng.exe > cmd.exe /c C:\\Scripts\\vss_health.cmd (signed script folder, unchanged since 2023)' },
      { id: 'r03', t: '01:00:04', src: 'process', host: 'SRV-FS02', user: 'svc_backup', type: 'Process create', msg: 'cmd.exe > vssadmin.exe list shadows /for=D:' },
      { id: 'r04', t: '01:00:05', src: 'process', host: 'SRV-FS02', user: 'svc_backup', type: 'Process create', msg: 'cmd.exe > vssadmin.exe list shadowstorage' },
      { id: 'r05', t: '01:00:07', src: 'winevt', host: 'SRV-FS02', user: 'SYSTEM', type: 'VSS 8224', msg: 'The VSS service is shutting down due to idle timeout (normal)' },
      { id: 'r06', t: '01:00:30', src: 'ops', host: 'BACKUP', user: '', type: 'Inventory', msg: 'SRV-FS02 shadow copies on D: 14 (same as yesterday, oldest 2026-09-09). No deletions recorded.' },
      { id: 'r07', t: '01:02:00', src: 'firewall', host: 'FW-CORE', user: '', type: 'ALLOW', msg: 'ALLOW TCP 10.20.30.12:51500 -> 10.20.30.14:445 rule=backup-to-fs' },
      { id: 'r08', t: '01:05:00', src: 'ops', host: 'SIEM', user: '', type: 'Rule history', msg: 'vss_shadow_manipulation v1: selection Image|endswith "\\vssadmin.exe" and CommandLine|contains "shadows". 0 hits in testing (tested only against a delete sample). 31 hits since deployment, all "vssadmin list shadows" from 9 servers.' },
      { id: 'r09', t: '01:06:00', src: 'ops', host: 'SIEM', user: '', type: 'Rule reference', msg: 'SigmaHQ reference rule matches CommandLine|contains|all: "delete", "shadows" (and resize shadowstorage with small maxsize)' },
      { id: 'r10', t: '01:10:00', src: 'process', host: 'SRV-FS02', user: 'svc_backup', type: 'Search', msg: 'No process on SRV-FS02 in 7 days with "delete shadows", "shadowcopy delete", "resize shadowstorage" or wbadmin delete catalog' },
      { id: 'r11', t: '01:12:00', src: 'winevt', host: 'SRV-FS02', user: '', type: 'Search', msg: 'No mass file renames, no new services, no logons from unusual hosts on SRV-FS02 in 24 h' },
    ],
    key: [
      { id: 'k-list', label: 'What ran was "vssadmin list", not delete', rows: ['r03', 'r04'], why: 'Listing shadow copies and their storage is a read-only health check. The alert title says deletion; the event does not show one.' },
      { id: 'k-rule', label: 'The rule matches any vssadmin command containing "shadows"', rows: ['r08'], why: 'The selection lacks "delete", so "list shadows" matches. It was only tested against a malicious sample, never against normal activity, and has fired 31 times on the same health check.' },
      { id: 'k-intact', label: 'Shadow copies are all still there', rows: ['r06'], why: 'The backup inventory shows the same 14 copies as yesterday: nothing was deleted.' },
    ],
    related: ['r01', 'r02', 'r09', 'r10', 'r11'],
    verdict: 'fp',
    parQueries: 3,
    writeup: [
      { label: 'Says only "list shadows" ran', any: ['list', 'read-only', 'health check'] },
      { label: 'Explains the rule logic flaw', any: ['delete', 'contains', 'selection', 'too broad'] },
      { label: 'Proposes a rule fix or test', any: ['tune', 'fix', 'add', 'test', 'known-good', 'sigmahq'] },
    ],
    explanation:
      'False positive: the alert says shadow copies were deleted, but only "vssadmin list shadows" and "list shadowstorage" ran as part of a nightly health check, and all 14 copies are intact. The rule is wrong: it matches any vssadmin command containing "shadows". Fix the rule (require "delete" together with "shadows", plus the resize shadowstorage variant, as in the SigmaHQ reference), add a known-good test sample, and redeploy. Do not filter out svc_backup or SRV-FS02: that would hide a real deletion there.',
    strong: [
      'Compare the alert title to the raw event: the rule said "deletion", the command line says "list".',
      'Check the effect, not just the command: the shadow copy inventory is unchanged.',
      'Fix the logic, not the noise: a host or account exclusion would blind the rule on exactly the servers ransomware targets.',
      'Detection-as-code lesson: test every rule against known-good activity as well as the malicious sample before deployment.',
    ],
  },

  // ------------------------------------------------------------------ L3-4: ambiguous cloud key
  {
    id: 'siem-l3-cloud-key',
    tier: 'l3',
    title: 'Same key, new network',
    difficulty: 3,
    ambiguous: true,
    date: 'Fri 25 Sep 2026',
    summary: 'The CI deploy key is calling AWS from an IP it has never used, in the middle of a CI migration. The old runner logs have already been deleted.',
    requires: { skills: ['l3-cloud'] },
    alert: {
      id: 'ALRT-6188',
      name: 'Long-term access key used from new network (AWS CloudTrail)',
      severity: 'high',
      time: '11:02:19',
      host: 'AWS 111122223333',
      user: 'ci-deploy',
      source: '198.51.100.23',
      detail: 'Access key AKIAIOSFODNN7EXAMPLE (IAM user ci-deploy) made its first API call from 198.51.100.23: sts GetCallerIdentity.',
    },
    logs: [
      { id: 'q01', t: '08:30:00', src: 'ops', host: 'CHANGE-CAL', user: '', type: 'Change window', msg: 'CHG-6120 (approved): migrate CI runners from on-prem (192.0.2.10) to a hosted runner provider this week. New egress range "to be confirmed by the vendor". Owner: platform team (r.ito).' },
      { id: 'q02', t: '09:15:00', src: 'ops', host: 'CI', user: '', type: 'Runner status', msg: 'Old runner 192.0.2.10 decommissioned 09:10; its job logs were deleted with the VM (retention not configured). New hosted runners: registration in progress.' },
      { id: 'q03', t: '10:48:00', src: 'cloud', host: 'AWS 111122223333', user: 'ci-deploy', type: 'ecr GetAuthorizationToken', msg: 'ecr GetAuthorizationToken  key=AKIAIOSFODNN7EXAMPLE  src=192.0.2.10  ua=Botocore/1.34  errorCode=null  (last call from the old runner)' },
      { id: 'q04', t: '11:02:19', src: 'cloud', host: 'AWS 111122223333', user: 'ci-deploy', type: 'sts GetCallerIdentity', msg: 'sts GetCallerIdentity  key=AKIAIOSFODNN7EXAMPLE  src=198.51.100.23  ua=aws-cli/2.17.4 os/linux  errorCode=null' },
      { id: 'q05', t: '11:02:40', src: 'cloud', host: 'AWS 111122223333', user: 'ci-deploy', type: 'iam ListAttachedUserPolicies', msg: 'iam ListAttachedUserPolicies user=ci-deploy  src=198.51.100.23  ua=aws-cli/2.17.4  errorCode=AccessDenied' },
      { id: 'q06', t: '11:03:05', src: 'cloud', host: 'AWS 111122223333', user: 'ci-deploy', type: 'ecr GetAuthorizationToken', msg: 'ecr GetAuthorizationToken  src=198.51.100.23  ua=aws-cli/2.17.4  errorCode=null' },
      { id: 'q07', t: '11:03:30', src: 'cloud', host: 'AWS 111122223333', user: 'ci-deploy', type: 's3 ListBuckets', msg: 's3 ListBuckets  src=198.51.100.23  ua=aws-cli/2.17.4  errorCode=null' },
      { id: 'q08', t: '11:04:10', src: 'cloud', host: 'AWS 111122223333', user: 'ci-deploy', type: 'ecs UpdateService', msg: 'ecs UpdateService cluster=prod service=web image=111122223333.dkr.ecr.eu-west-1/web:4.18.2  src=198.51.100.23  errorCode=null' },
      { id: 'q09', t: '11:05:00', src: 'ops', host: 'DIRECTORY', user: '', type: 'IP info', msg: '198.51.100.23: hosting provider network. The runner vendor\'s published ranges list 198.51.100.0/25 for "legacy regions"; the vendor\'s page was last updated 2025.' },
      { id: 'q10', t: '11:06:30', src: 'ops', host: 'CI', user: '', type: 'Pipeline', msg: 'Git: release tag web 4.18.2 pushed 10:58 by r.ito; no pipeline run is recorded for it (new runner logs not yet connected to the SIEM)' },
      { id: 'q11', t: '11:07:00', src: 'cloud', host: 'AWS 111122223333', user: '', type: 'Search', msg: 'No CreateUser, CreateAccessKey, AttachUserPolicy, PutBucketPolicy, DeletePublicAccessBlock or StopLogging in the account today' },
      { id: 'q12', t: '11:08:00', src: 'ops', host: 'SECRETS', user: '', type: 'Key info', msg: 'AKIAIOSFODNN7EXAMPLE created 2022, never rotated. Stored in the old runner config and in r.ito\'s laptop profile for manual deploys.' },
    ],
    key: [
      { id: 'k-new', label: 'First use from a new hosting IP, with a CLI user agent', rows: ['q04'], why: 'Everything before came from the runner (192.0.2.10) with the SDK user agent. A new IP, aws-cli and GetCallerIdentity first is exactly how a stolen key is tested.' },
      { id: 'k-probe', label: 'A permission probe that failed', rows: ['q05'], why: 'Asking IAM what policies the key has (and being denied) is enumeration. A CI pipeline knows what it is allowed to do and does not ask.' },
      { id: 'k-deploy', label: 'Then a real production deploy of the new release', rows: ['q08'], why: 'UpdateService with the release just tagged by r.ito looks like a genuine deploy. An attacker could do the same, but it matches the story of a migrated pipeline or a manual deploy.' },
      { id: 'k-gap', label: 'No runner logs on either side', rows: ['q02', 'q10'], why: 'The old runner\'s logs are gone and the new runner\'s are not in the SIEM: nothing shows which machine made these calls.' },
    ],
    related: ['q01', 'q03', 'q06', 'q07', 'q09', 'q11', 'q12'],
    verdict: 'tp',
    defensible: { tp: 1, btp: 0.6 },
    confidence: { low: 0.5, medium: 1, high: 0 },
    parQueries: 4,
    gaps: [
      { id: 'gq-who', correct: true, text: 'Whether the calls came from the new hosted runner, r.ito\'s laptop, or someone else.', why: 'The runner logs are the missing link: the new runner\'s job log (or r.ito himself) settles it.' },
      { id: 'gq-range', correct: true, text: 'Whether 198.51.100.23 really belongs to the runner vendor for this account.', why: 'The published range is stale. The vendor or the runner\'s own egress IP confirms it.' },
      { id: 'gq-cli', correct: true, text: 'Why a pipeline would use aws-cli and probe its own permissions.', why: 'A pipeline built on the SDK does not switch to the CLI and ask IAM what it may do, but a human debugging a new runner might.' },
      { id: 'gq-cloudtrail', correct: false, text: 'Whether CloudTrail recorded the calls correctly.', why: 'CloudTrail is the reliable part here: the calls, IPs and user agents are facts.' },
      { id: 'gq-deploy', correct: false, text: 'Whether ECS actually deployed version 4.18.2.', why: 'It did (errorCode=null). Whether the deploy happened is not in doubt, only who triggered it.' },
      { id: 'gq-none', correct: false, text: 'Nothing: the migration ticket explains it.', why: 'The ticket does not name the IP, and the CLI probe does not fit a pipeline. It supports one story without proving it.' },
    ],
    steps: {
      'verify-user': { rating: 'best', why: 'Call r.ito: did the new runner or he himself deploy 4.18.2 from 198.51.100.23 at 11:04, and did he run aws-cli against IAM?' },
      'more-logs': { rating: 'best', why: 'Get the new runner\'s job log and egress IP from the vendor console, and check r.ito\'s laptop for aws-cli history.' },
      escalate: { rating: 'best', why: 'Escalate as a possible leaked long-term key at medium confidence, stating the migration and the missing runner logs. A key that deploys to production is high impact.' },
      contain: { rating: 'ok', why: 'Deactivating the key breaks deploys mid-migration, but it is defensible if r.ito cannot be reached quickly. Rotating it is overdue anyway (never rotated since 2022).' },
      'check-edr': { rating: 'ok', why: 'Checking r.ito\'s laptop in EDR for aws-cli runs is useful, though the hosted runner is outside EDR coverage.' },
      close: { rating: 'bad', why: 'An unrotated production deploy key used from an unconfirmed IP with a permission probe cannot be closed on the strength of a change ticket.' },
      wait: { rating: 'bad', why: 'If the key is stolen, the next calls could be persistence or data theft. Waiting gives the attacker time.' },
      reimage: { rating: 'bad', why: 'There is no host to reimage: the key is the credential that matters, and wiping a laptop would destroy the evidence.' },
    },
    writeup: [
      { label: 'Says what cannot be confirmed', any: ['cannot', "can't", 'unable', 'unclear', 'unknown', 'unverified', 'not sure', 'uncertain', 'missing'] },
      { label: 'Names the stolen-key pattern', any: ['getcalleridentity', 'enumerat', 'probe', 'accessdenied', 'whoami'] },
      { label: 'Mentions the migration or runner', any: ['migration', 'runner', 'chg-6120'] },
      { label: 'Proposes verifying with r.ito or rotating the key', any: ['verify', 'confirm', 'call', 'r.ito', 'rotate'] },
    ],
    explanation:
      'Genuinely ambiguous. GetCallerIdentity from a new hosting IP with aws-cli, followed by a failed IAM permission probe, is the classic first move with a leaked key. The CI migration, the vendor\'s (stale) range and a deploy of the release r.ito just tagged all point to the new runner or r.ito himself. The runner logs that would settle it are missing on both sides. The stronger call is a suspected true positive at medium confidence: verify with r.ito, get the runner\'s egress IP, and rotate a key that has not changed since 2022. Calling it a benign true positive (the migration) is defensible if you verify before closing.',
    strong: [
      'Compare against the key\'s baseline: IP, user agent and API set all changed at once.',
      'Separate the facts (CloudTrail calls) from the story (the migration). The ticket does not name the IP.',
      'Notice the detail that does not fit a pipeline: a CLI permission probe against IAM.',
      'Think about impact: this key deploys to production and has never been rotated. Moving CI to short-lived OIDC role credentials removes the problem.',
    ],
    arguments: {
      tp: 'A never-rotated production key appears on a new hosting IP, starts with whoami and a permission probe from the CLI, and nothing shows which machine made the calls. That is the stolen-key playbook.',
      btp: 'The runners are migrating to a hosting provider this week, the IP sits in a range the vendor publishes, and the only change made was deploying the release r.ito tagged four minutes earlier. No persistence or evasion happened.',
    },
    settle: [
      'r.ito confirming by phone that he ran the CLI from the new runner (or his laptop) to test it.',
      'The new runner\'s job log and egress IP from the vendor console.',
      'Any further calls from 198.51.100.23 outside the deploy pattern (IAM changes, bucket policy, new keys).',
    ],
    outcome: {
      title: 'r.ito was debugging the new runner',
      verdict: 'btp',
      text: 'r.ito answered at 11:20: the first hosted runner job failed, so he opened a shell on the runner and ran aws-cli by hand, including a check of the key\'s policies, then triggered the deploy. The vendor confirmed 198.51.100.23 as the runner\'s egress IP. The key was rotated that afternoon and the pipeline moved to OIDC role credentials the following week. A careful "suspected true positive, verify" was the right call at 11:02: nothing in the SIEM could tell r.ito from a thief.',
    },
  },
];
